// Code generated by Oct's compiled backend. DO NOT EDIT.
package specialized

import (
	"encoding/json"
	"fmt"
)

type __octVoid struct{}

type octResult_Int struct {
	Value int
	Err   string
	IsErr bool
}

type Main_Job struct {
	ID     int
	Status int
}

type Main_FilterOnlyBoardSnapshot struct {
	Cursor  int
	Emitted int
}

type Main_FilterTake10BoardSnapshot struct {
	Cursor  int
	Emitted int
}

type Main_FilterMapBoardSnapshot struct {
	Cursor  int
	Emitted int
}

type Main_CountAllBoardSnapshot struct {
	Cursor  int
	Emitted int
}

type __octFlowInstance_Void interface {
	__octStep(any)
	__octActive() string
	__octComplete() bool
	__octDidYield() bool
	__octYielded() (any, bool)
	__octResult() (__octVoid, bool)
	__octStateHistory() []string
	__octResumeTarget() string
	__octBoardSnapshot() (any, bool)
}

type __octResultFlow_Void struct {
	Value __octVoid
	Err   string
	IsErr bool
}

type __octFlow_Main_FilterOnly struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	lastYield    Main_Job
	hasYield     bool
	jobs         []Main_Job
	board        struct {
		Cursor  int
		Emitted int
	}
}

func fn_Main_FilterOnly(jobs []Main_Job) __octFlowInstance_Void {
	__flow := &__octFlow_Main_FilterOnly{}
	__flow.jobs = jobs
	return __flow
}

func (f *__octFlow_Main_FilterOnly) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Scan"
	default:
		return ""
	}
}

func (f *__octFlow_Main_FilterOnly) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_FilterOnly) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_FilterOnly) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_FilterOnly) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_FilterOnly) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_FilterOnly) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_FilterOnly) __octBoardSnapshot() (any, bool) {
	return Main_FilterOnlyBoardSnapshot{
		Cursor:  f.board.Cursor,
		Emitted: f.board.Emitted,
	}, true
}

func (f *__octFlow_Main_FilterOnly) __octStep(__input any) {
	var item Main_Job
	if __input != nil {
		panic("runtime invariant violation: input supplied to non-input flow")
	}
	if f.completed {
		return
	}
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.board.Cursor >= len(f.jobs) {
					f.result = __octVoid{}
					f.completed = true
					f.hasResult = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 1:
				item = f.jobs[f.board.Cursor]
				f.instruction++
				continue
			case 2:
				f.board.Cursor = (f.board.Cursor + 1)
				f.instruction++
				continue
			case 3:
				if fn_Main_IsReady(item) {
					f.board.Emitted = (f.board.Emitted + 1)
					f.lastYield = item
					f.hasYield = true
					f.instruction++
					return
				}
				f.instruction++
				continue
			case 4:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Scan exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Main_FilterTake10 struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	lastYield    Main_Job
	hasYield     bool
	jobs         []Main_Job
	board        struct {
		Cursor  int
		Emitted int
	}
}

func fn_Main_FilterTake10(jobs []Main_Job) __octFlowInstance_Void {
	__flow := &__octFlow_Main_FilterTake10{}
	__flow.jobs = jobs
	return __flow
}

func (f *__octFlow_Main_FilterTake10) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Scan"
	default:
		return ""
	}
}

func (f *__octFlow_Main_FilterTake10) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_FilterTake10) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_FilterTake10) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_FilterTake10) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_FilterTake10) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_FilterTake10) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_FilterTake10) __octBoardSnapshot() (any, bool) {
	return Main_FilterTake10BoardSnapshot{
		Cursor:  f.board.Cursor,
		Emitted: f.board.Emitted,
	}, true
}

func (f *__octFlow_Main_FilterTake10) __octStep(__input any) {
	var item Main_Job
	if __input != nil {
		panic("runtime invariant violation: input supplied to non-input flow")
	}
	if f.completed {
		return
	}
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.board.Emitted >= 10 {
					f.result = __octVoid{}
					f.completed = true
					f.hasResult = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 1:
				if f.board.Cursor >= len(f.jobs) {
					f.result = __octVoid{}
					f.completed = true
					f.hasResult = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 2:
				item = f.jobs[f.board.Cursor]
				f.instruction++
				continue
			case 3:
				f.board.Cursor = (f.board.Cursor + 1)
				f.instruction++
				continue
			case 4:
				if fn_Main_IsReady(item) {
					f.board.Emitted = (f.board.Emitted + 1)
					f.lastYield = item
					f.hasYield = true
					f.instruction++
					return
				}
				f.instruction++
				continue
			case 5:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Scan exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Main_FilterMap struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	lastYield    int
	hasYield     bool
	jobs         []Main_Job
	board        struct {
		Cursor  int
		Emitted int
	}
}

func fn_Main_FilterMap(jobs []Main_Job) __octFlowInstance_Void {
	__flow := &__octFlow_Main_FilterMap{}
	__flow.jobs = jobs
	return __flow
}

func (f *__octFlow_Main_FilterMap) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Scan"
	default:
		return ""
	}
}

func (f *__octFlow_Main_FilterMap) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_FilterMap) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_FilterMap) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_FilterMap) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_FilterMap) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_FilterMap) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_FilterMap) __octBoardSnapshot() (any, bool) {
	return Main_FilterMapBoardSnapshot{
		Cursor:  f.board.Cursor,
		Emitted: f.board.Emitted,
	}, true
}

func (f *__octFlow_Main_FilterMap) __octStep(__input any) {
	var item Main_Job
	if __input != nil {
		panic("runtime invariant violation: input supplied to non-input flow")
	}
	if f.completed {
		return
	}
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.board.Cursor >= len(f.jobs) {
					f.result = __octVoid{}
					f.completed = true
					f.hasResult = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 1:
				item = f.jobs[f.board.Cursor]
				f.instruction++
				continue
			case 2:
				f.board.Cursor = (f.board.Cursor + 1)
				f.instruction++
				continue
			case 3:
				if fn_Main_IsReady(item) {
					f.board.Emitted = (f.board.Emitted + 1)
					f.lastYield = fn_Main_JobID(item)
					f.hasYield = true
					f.instruction++
					return
				}
				f.instruction++
				continue
			case 4:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Scan exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Main_CountAll struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	lastYield    Main_Job
	hasYield     bool
	jobs         []Main_Job
	board        struct {
		Cursor  int
		Emitted int
	}
}

func fn_Main_CountAll(jobs []Main_Job) __octFlowInstance_Void {
	__flow := &__octFlow_Main_CountAll{}
	__flow.jobs = jobs
	return __flow
}

func (f *__octFlow_Main_CountAll) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Scan"
	default:
		return ""
	}
}

func (f *__octFlow_Main_CountAll) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_CountAll) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_CountAll) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_CountAll) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_CountAll) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_CountAll) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_CountAll) __octBoardSnapshot() (any, bool) {
	return Main_CountAllBoardSnapshot{
		Cursor:  f.board.Cursor,
		Emitted: f.board.Emitted,
	}, true
}

func (f *__octFlow_Main_CountAll) __octStep(__input any) {
	var item Main_Job
	if __input != nil {
		panic("runtime invariant violation: input supplied to non-input flow")
	}
	if f.completed {
		return
	}
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.board.Cursor >= len(f.jobs) {
					f.result = __octVoid{}
					f.completed = true
					f.hasResult = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 1:
				item = f.jobs[f.board.Cursor]
				f.instruction++
				continue
			case 2:
				f.board.Cursor = (f.board.Cursor + 1)
				f.instruction++
				continue
			case 3:
				if true {
					f.board.Emitted = (f.board.Emitted + 1)
					f.lastYield = item
					f.hasYield = true
					f.instruction++
					return
				}
				f.instruction++
				continue
			case 4:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Scan exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

// FilterOnly is the generated, typed host facade for the Oct flow Main.FilterOnly.
type FilterOnly struct{ flow *__octFlow_Main_FilterOnly }

func NewFilterOnly(jobs []Main_Job) *FilterOnly {
	return &FilterOnly{flow: fn_Main_FilterOnly(jobs).(*__octFlow_Main_FilterOnly)}
}

type FilterOnlyTurn struct{ machine *FilterOnly }

func (m *FilterOnly) Step() (turn FilterOnlyTurn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	m.flow.__octStep(nil)
	return FilterOnlyTurn{machine: m}, nil
}

func (t FilterOnlyTurn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t FilterOnlyTurn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t FilterOnlyTurn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t FilterOnlyTurn) Yielded() (Main_Job, error) {
	var zero Main_Job
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(Main_Job)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *FilterOnly) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

func (m *FilterOnly) Board() (Main_FilterOnlyBoardSnapshot, error) {
	var zero Main_FilterOnlyBoardSnapshot
	if m == nil || m.flow == nil {
		return zero, fmt.Errorf("flow machine is nil")
	}
	value, ok := m.flow.__octBoardSnapshot()
	if !ok {
		return zero, fmt.Errorf("flow has no board")
	}
	return value.(Main_FilterOnlyBoardSnapshot), nil
}

type FilterOnlyCheckpointReason string

const (
	FilterOnlyVersionMismatch      FilterOnlyCheckpointReason = "CheckpointVersionMismatch"
	FilterOnlyFlowMismatch         FilterOnlyCheckpointReason = "FlowMismatch"
	FilterOnlyFingerprintMismatch  FilterOnlyCheckpointReason = "FlowFingerprintMismatch"
	FilterOnlySchemaMismatch       FilterOnlyCheckpointReason = "SchemaMismatch"
	FilterOnlyStateMissing         FilterOnlyCheckpointReason = "StateMissing"
	FilterOnlyContinuationInvalid  FilterOnlyCheckpointReason = "ContinuationPositionInvalid"
	FilterOnlyBoardSchemaMismatch  FilterOnlyCheckpointReason = "BoardSchemaMismatch"
	FilterOnlyConstructionMismatch FilterOnlyCheckpointReason = "ConstructionParameterMismatch"
	FilterOnlyUtilitySiteMismatch  FilterOnlyCheckpointReason = "UtilitySiteMismatch"
	FilterOnlyYieldSchemaMismatch  FilterOnlyCheckpointReason = "YieldSchemaMismatch"
	FilterOnlyNotAtYield           FilterOnlyCheckpointReason = "NotAtYieldBoundary"
)

type FilterOnlyCheckpointError struct {
	Reason FilterOnlyCheckpointReason
	Detail string
}

func (e FilterOnlyCheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octFilterOnlyCheckpointError(reason FilterOnlyCheckpointReason, detail string) error {
	return FilterOnlyCheckpointError{Reason: reason, Detail: detail}
}

type FilterOnlyCheckpoint struct{ data []byte }

func (c FilterOnlyCheckpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseFilterOnlyCheckpoint(data []byte) (FilterOnlyCheckpoint, error) {
	var payload __octFilterOnlyCheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return FilterOnlyCheckpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return FilterOnlyCheckpoint{data: out}, nil
}

type __octFilterOnlyCheckpointBoard struct {
	Cursor  int `json:"Cursor"`
	Emitted int `json:"Emitted"`
}

type __octFilterOnlyCheckpointPayload struct {
	Version            int                            `json:"version"`
	Package            string                         `json:"package"`
	Flow               string                         `json:"flow"`
	Fingerprint        string                         `json:"fingerprint"`
	BoardSchema        string                         `json:"board_schema"`
	ConstructionSchema string                         `json:"construction_schema"`
	UtilitySchema      string                         `json:"utility_schema"`
	YieldSchema        string                         `json:"yield_schema"`
	CurrentState       string                         `json:"current_state"`
	Instruction        int                            `json:"instruction"`
	Parameterjobs      []Main_Job                     `json:"parameter_jobs"`
	Board              __octFilterOnlyCheckpointBoard `json:"board"`
	LastYield          Main_Job                       `json:"last_yield"`
	HasYield           bool                           `json:"has_yield"`
}

func (m *FilterOnly) Checkpoint() (FilterOnlyCheckpoint, error) {
	if m == nil || m.flow == nil {
		return FilterOnlyCheckpoint{}, __octFilterOnlyCheckpointError(FilterOnlyNotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return FilterOnlyCheckpoint{}, __octFilterOnlyCheckpointError(FilterOnlyNotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octFilterOnlyCheckpointPayload{Version: 1, Package: "Main", Flow: "FilterOnly", Fingerprint: "e63e09b032b6d78c44b6fdef2ac0dc49e9d674d2f578fe8cd0708766e6040246", BoardSchema: "Cursor:Int;Emitted:Int;", ConstructionSchema: "jobs:Main.Job[];", UtilitySchema: "", YieldSchema: "Main.Job", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	payload.Parameterjobs = m.flow.jobs
	payload.Board = __octFilterOnlyCheckpointBoard{Cursor: m.flow.board.Cursor, Emitted: m.flow.board.Emitted}
	data, err := json.Marshal(payload)
	if err != nil {
		return FilterOnlyCheckpoint{}, err
	}
	return FilterOnlyCheckpoint{data: data}, nil
}

func RestoreFilterOnly(checkpoint FilterOnlyCheckpoint) (*FilterOnly, error) {
	var payload __octFilterOnlyCheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyVersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "FilterOnly" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyFlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "e63e09b032b6d78c44b6fdef2ac0dc49e9d674d2f578fe8cd0708766e6040246" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyFingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "Cursor:Int;Emitted:Int;" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyBoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "jobs:Main.Job[];" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyUtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Main.Job" {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyYieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyYieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octFilterOnlyStateID(payload.CurrentState)
	if !ok {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyStateMissing, payload.CurrentState)
	}
	if !__octFilterOnlyContinuationValid(stateID, payload.Instruction) {
		return nil, __octFilterOnlyCheckpointError(FilterOnlyContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_FilterOnly{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	flow.jobs = payload.Parameterjobs
	flow.board.Cursor = payload.Board.Cursor
	flow.board.Emitted = payload.Board.Emitted
	return &FilterOnly{flow: flow}, nil
}

func __octFilterOnlyStateID(name string) (int, bool) {
	switch name {
	case "Scan":
		return 0, true
	default:
		return 0, false
	}
}
func __octFilterOnlyContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 5
	default:
		return false
	}
}

// FilterTake10 is the generated, typed host facade for the Oct flow Main.FilterTake10.
type FilterTake10 struct{ flow *__octFlow_Main_FilterTake10 }

func NewFilterTake10(jobs []Main_Job) *FilterTake10 {
	return &FilterTake10{flow: fn_Main_FilterTake10(jobs).(*__octFlow_Main_FilterTake10)}
}

type FilterTake10Turn struct{ machine *FilterTake10 }

func (m *FilterTake10) Step() (turn FilterTake10Turn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	m.flow.__octStep(nil)
	return FilterTake10Turn{machine: m}, nil
}

func (t FilterTake10Turn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t FilterTake10Turn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t FilterTake10Turn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t FilterTake10Turn) Yielded() (Main_Job, error) {
	var zero Main_Job
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(Main_Job)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *FilterTake10) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

func (m *FilterTake10) Board() (Main_FilterTake10BoardSnapshot, error) {
	var zero Main_FilterTake10BoardSnapshot
	if m == nil || m.flow == nil {
		return zero, fmt.Errorf("flow machine is nil")
	}
	value, ok := m.flow.__octBoardSnapshot()
	if !ok {
		return zero, fmt.Errorf("flow has no board")
	}
	return value.(Main_FilterTake10BoardSnapshot), nil
}

type FilterTake10CheckpointReason string

const (
	FilterTake10VersionMismatch      FilterTake10CheckpointReason = "CheckpointVersionMismatch"
	FilterTake10FlowMismatch         FilterTake10CheckpointReason = "FlowMismatch"
	FilterTake10FingerprintMismatch  FilterTake10CheckpointReason = "FlowFingerprintMismatch"
	FilterTake10SchemaMismatch       FilterTake10CheckpointReason = "SchemaMismatch"
	FilterTake10StateMissing         FilterTake10CheckpointReason = "StateMissing"
	FilterTake10ContinuationInvalid  FilterTake10CheckpointReason = "ContinuationPositionInvalid"
	FilterTake10BoardSchemaMismatch  FilterTake10CheckpointReason = "BoardSchemaMismatch"
	FilterTake10ConstructionMismatch FilterTake10CheckpointReason = "ConstructionParameterMismatch"
	FilterTake10UtilitySiteMismatch  FilterTake10CheckpointReason = "UtilitySiteMismatch"
	FilterTake10YieldSchemaMismatch  FilterTake10CheckpointReason = "YieldSchemaMismatch"
	FilterTake10NotAtYield           FilterTake10CheckpointReason = "NotAtYieldBoundary"
)

type FilterTake10CheckpointError struct {
	Reason FilterTake10CheckpointReason
	Detail string
}

func (e FilterTake10CheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octFilterTake10CheckpointError(reason FilterTake10CheckpointReason, detail string) error {
	return FilterTake10CheckpointError{Reason: reason, Detail: detail}
}

type FilterTake10Checkpoint struct{ data []byte }

func (c FilterTake10Checkpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseFilterTake10Checkpoint(data []byte) (FilterTake10Checkpoint, error) {
	var payload __octFilterTake10CheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return FilterTake10Checkpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return FilterTake10Checkpoint{data: out}, nil
}

type __octFilterTake10CheckpointBoard struct {
	Cursor  int `json:"Cursor"`
	Emitted int `json:"Emitted"`
}

type __octFilterTake10CheckpointPayload struct {
	Version            int                              `json:"version"`
	Package            string                           `json:"package"`
	Flow               string                           `json:"flow"`
	Fingerprint        string                           `json:"fingerprint"`
	BoardSchema        string                           `json:"board_schema"`
	ConstructionSchema string                           `json:"construction_schema"`
	UtilitySchema      string                           `json:"utility_schema"`
	YieldSchema        string                           `json:"yield_schema"`
	CurrentState       string                           `json:"current_state"`
	Instruction        int                              `json:"instruction"`
	Parameterjobs      []Main_Job                       `json:"parameter_jobs"`
	Board              __octFilterTake10CheckpointBoard `json:"board"`
	LastYield          Main_Job                         `json:"last_yield"`
	HasYield           bool                             `json:"has_yield"`
}

func (m *FilterTake10) Checkpoint() (FilterTake10Checkpoint, error) {
	if m == nil || m.flow == nil {
		return FilterTake10Checkpoint{}, __octFilterTake10CheckpointError(FilterTake10NotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return FilterTake10Checkpoint{}, __octFilterTake10CheckpointError(FilterTake10NotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octFilterTake10CheckpointPayload{Version: 1, Package: "Main", Flow: "FilterTake10", Fingerprint: "30f86f8d478ffb329725113e8192c3499d4b885bf8df5c9bbe0ade012d7841ff", BoardSchema: "Cursor:Int;Emitted:Int;", ConstructionSchema: "jobs:Main.Job[];", UtilitySchema: "", YieldSchema: "Main.Job", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	payload.Parameterjobs = m.flow.jobs
	payload.Board = __octFilterTake10CheckpointBoard{Cursor: m.flow.board.Cursor, Emitted: m.flow.board.Emitted}
	data, err := json.Marshal(payload)
	if err != nil {
		return FilterTake10Checkpoint{}, err
	}
	return FilterTake10Checkpoint{data: data}, nil
}

func RestoreFilterTake10(checkpoint FilterTake10Checkpoint) (*FilterTake10, error) {
	var payload __octFilterTake10CheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octFilterTake10CheckpointError(FilterTake10VersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "FilterTake10" {
		return nil, __octFilterTake10CheckpointError(FilterTake10FlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "30f86f8d478ffb329725113e8192c3499d4b885bf8df5c9bbe0ade012d7841ff" {
		return nil, __octFilterTake10CheckpointError(FilterTake10FingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "Cursor:Int;Emitted:Int;" {
		return nil, __octFilterTake10CheckpointError(FilterTake10BoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "jobs:Main.Job[];" {
		return nil, __octFilterTake10CheckpointError(FilterTake10ConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octFilterTake10CheckpointError(FilterTake10UtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Main.Job" {
		return nil, __octFilterTake10CheckpointError(FilterTake10YieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octFilterTake10CheckpointError(FilterTake10YieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octFilterTake10StateID(payload.CurrentState)
	if !ok {
		return nil, __octFilterTake10CheckpointError(FilterTake10StateMissing, payload.CurrentState)
	}
	if !__octFilterTake10ContinuationValid(stateID, payload.Instruction) {
		return nil, __octFilterTake10CheckpointError(FilterTake10ContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_FilterTake10{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	flow.jobs = payload.Parameterjobs
	flow.board.Cursor = payload.Board.Cursor
	flow.board.Emitted = payload.Board.Emitted
	return &FilterTake10{flow: flow}, nil
}

func __octFilterTake10StateID(name string) (int, bool) {
	switch name {
	case "Scan":
		return 0, true
	default:
		return 0, false
	}
}
func __octFilterTake10ContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 6
	default:
		return false
	}
}

// FilterMap is the generated, typed host facade for the Oct flow Main.FilterMap.
type FilterMap struct{ flow *__octFlow_Main_FilterMap }

func NewFilterMap(jobs []Main_Job) *FilterMap {
	return &FilterMap{flow: fn_Main_FilterMap(jobs).(*__octFlow_Main_FilterMap)}
}

type FilterMapTurn struct{ machine *FilterMap }

func (m *FilterMap) Step() (turn FilterMapTurn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	m.flow.__octStep(nil)
	return FilterMapTurn{machine: m}, nil
}

func (t FilterMapTurn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t FilterMapTurn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t FilterMapTurn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t FilterMapTurn) Yielded() (int, error) {
	var zero int
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(int)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *FilterMap) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

func (m *FilterMap) Board() (Main_FilterMapBoardSnapshot, error) {
	var zero Main_FilterMapBoardSnapshot
	if m == nil || m.flow == nil {
		return zero, fmt.Errorf("flow machine is nil")
	}
	value, ok := m.flow.__octBoardSnapshot()
	if !ok {
		return zero, fmt.Errorf("flow has no board")
	}
	return value.(Main_FilterMapBoardSnapshot), nil
}

type FilterMapCheckpointReason string

const (
	FilterMapVersionMismatch      FilterMapCheckpointReason = "CheckpointVersionMismatch"
	FilterMapFlowMismatch         FilterMapCheckpointReason = "FlowMismatch"
	FilterMapFingerprintMismatch  FilterMapCheckpointReason = "FlowFingerprintMismatch"
	FilterMapSchemaMismatch       FilterMapCheckpointReason = "SchemaMismatch"
	FilterMapStateMissing         FilterMapCheckpointReason = "StateMissing"
	FilterMapContinuationInvalid  FilterMapCheckpointReason = "ContinuationPositionInvalid"
	FilterMapBoardSchemaMismatch  FilterMapCheckpointReason = "BoardSchemaMismatch"
	FilterMapConstructionMismatch FilterMapCheckpointReason = "ConstructionParameterMismatch"
	FilterMapUtilitySiteMismatch  FilterMapCheckpointReason = "UtilitySiteMismatch"
	FilterMapYieldSchemaMismatch  FilterMapCheckpointReason = "YieldSchemaMismatch"
	FilterMapNotAtYield           FilterMapCheckpointReason = "NotAtYieldBoundary"
)

type FilterMapCheckpointError struct {
	Reason FilterMapCheckpointReason
	Detail string
}

func (e FilterMapCheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octFilterMapCheckpointError(reason FilterMapCheckpointReason, detail string) error {
	return FilterMapCheckpointError{Reason: reason, Detail: detail}
}

type FilterMapCheckpoint struct{ data []byte }

func (c FilterMapCheckpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseFilterMapCheckpoint(data []byte) (FilterMapCheckpoint, error) {
	var payload __octFilterMapCheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return FilterMapCheckpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return FilterMapCheckpoint{data: out}, nil
}

type __octFilterMapCheckpointBoard struct {
	Cursor  int `json:"Cursor"`
	Emitted int `json:"Emitted"`
}

type __octFilterMapCheckpointPayload struct {
	Version            int                           `json:"version"`
	Package            string                        `json:"package"`
	Flow               string                        `json:"flow"`
	Fingerprint        string                        `json:"fingerprint"`
	BoardSchema        string                        `json:"board_schema"`
	ConstructionSchema string                        `json:"construction_schema"`
	UtilitySchema      string                        `json:"utility_schema"`
	YieldSchema        string                        `json:"yield_schema"`
	CurrentState       string                        `json:"current_state"`
	Instruction        int                           `json:"instruction"`
	Parameterjobs      []Main_Job                    `json:"parameter_jobs"`
	Board              __octFilterMapCheckpointBoard `json:"board"`
	LastYield          int                           `json:"last_yield"`
	HasYield           bool                          `json:"has_yield"`
}

func (m *FilterMap) Checkpoint() (FilterMapCheckpoint, error) {
	if m == nil || m.flow == nil {
		return FilterMapCheckpoint{}, __octFilterMapCheckpointError(FilterMapNotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return FilterMapCheckpoint{}, __octFilterMapCheckpointError(FilterMapNotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octFilterMapCheckpointPayload{Version: 1, Package: "Main", Flow: "FilterMap", Fingerprint: "470d2dcbc4688f6084ab2204688736c27499c10a345aa85c568ed22b39589b98", BoardSchema: "Cursor:Int;Emitted:Int;", ConstructionSchema: "jobs:Main.Job[];", UtilitySchema: "", YieldSchema: "Int", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	payload.Parameterjobs = m.flow.jobs
	payload.Board = __octFilterMapCheckpointBoard{Cursor: m.flow.board.Cursor, Emitted: m.flow.board.Emitted}
	data, err := json.Marshal(payload)
	if err != nil {
		return FilterMapCheckpoint{}, err
	}
	return FilterMapCheckpoint{data: data}, nil
}

func RestoreFilterMap(checkpoint FilterMapCheckpoint) (*FilterMap, error) {
	var payload __octFilterMapCheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octFilterMapCheckpointError(FilterMapVersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "FilterMap" {
		return nil, __octFilterMapCheckpointError(FilterMapFlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "470d2dcbc4688f6084ab2204688736c27499c10a345aa85c568ed22b39589b98" {
		return nil, __octFilterMapCheckpointError(FilterMapFingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "Cursor:Int;Emitted:Int;" {
		return nil, __octFilterMapCheckpointError(FilterMapBoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "jobs:Main.Job[];" {
		return nil, __octFilterMapCheckpointError(FilterMapConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octFilterMapCheckpointError(FilterMapUtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Int" {
		return nil, __octFilterMapCheckpointError(FilterMapYieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octFilterMapCheckpointError(FilterMapYieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octFilterMapStateID(payload.CurrentState)
	if !ok {
		return nil, __octFilterMapCheckpointError(FilterMapStateMissing, payload.CurrentState)
	}
	if !__octFilterMapContinuationValid(stateID, payload.Instruction) {
		return nil, __octFilterMapCheckpointError(FilterMapContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_FilterMap{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	flow.jobs = payload.Parameterjobs
	flow.board.Cursor = payload.Board.Cursor
	flow.board.Emitted = payload.Board.Emitted
	return &FilterMap{flow: flow}, nil
}

func __octFilterMapStateID(name string) (int, bool) {
	switch name {
	case "Scan":
		return 0, true
	default:
		return 0, false
	}
}
func __octFilterMapContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 5
	default:
		return false
	}
}

// CountAll is the generated, typed host facade for the Oct flow Main.CountAll.
type CountAll struct{ flow *__octFlow_Main_CountAll }

func NewCountAll(jobs []Main_Job) *CountAll {
	return &CountAll{flow: fn_Main_CountAll(jobs).(*__octFlow_Main_CountAll)}
}

type CountAllTurn struct{ machine *CountAll }

func (m *CountAll) Step() (turn CountAllTurn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	m.flow.__octStep(nil)
	return CountAllTurn{machine: m}, nil
}

func (t CountAllTurn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t CountAllTurn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t CountAllTurn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t CountAllTurn) Yielded() (Main_Job, error) {
	var zero Main_Job
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(Main_Job)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *CountAll) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

func (m *CountAll) Board() (Main_CountAllBoardSnapshot, error) {
	var zero Main_CountAllBoardSnapshot
	if m == nil || m.flow == nil {
		return zero, fmt.Errorf("flow machine is nil")
	}
	value, ok := m.flow.__octBoardSnapshot()
	if !ok {
		return zero, fmt.Errorf("flow has no board")
	}
	return value.(Main_CountAllBoardSnapshot), nil
}

type CountAllCheckpointReason string

const (
	CountAllVersionMismatch      CountAllCheckpointReason = "CheckpointVersionMismatch"
	CountAllFlowMismatch         CountAllCheckpointReason = "FlowMismatch"
	CountAllFingerprintMismatch  CountAllCheckpointReason = "FlowFingerprintMismatch"
	CountAllSchemaMismatch       CountAllCheckpointReason = "SchemaMismatch"
	CountAllStateMissing         CountAllCheckpointReason = "StateMissing"
	CountAllContinuationInvalid  CountAllCheckpointReason = "ContinuationPositionInvalid"
	CountAllBoardSchemaMismatch  CountAllCheckpointReason = "BoardSchemaMismatch"
	CountAllConstructionMismatch CountAllCheckpointReason = "ConstructionParameterMismatch"
	CountAllUtilitySiteMismatch  CountAllCheckpointReason = "UtilitySiteMismatch"
	CountAllYieldSchemaMismatch  CountAllCheckpointReason = "YieldSchemaMismatch"
	CountAllNotAtYield           CountAllCheckpointReason = "NotAtYieldBoundary"
)

type CountAllCheckpointError struct {
	Reason CountAllCheckpointReason
	Detail string
}

func (e CountAllCheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octCountAllCheckpointError(reason CountAllCheckpointReason, detail string) error {
	return CountAllCheckpointError{Reason: reason, Detail: detail}
}

type CountAllCheckpoint struct{ data []byte }

func (c CountAllCheckpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseCountAllCheckpoint(data []byte) (CountAllCheckpoint, error) {
	var payload __octCountAllCheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return CountAllCheckpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return CountAllCheckpoint{data: out}, nil
}

type __octCountAllCheckpointBoard struct {
	Cursor  int `json:"Cursor"`
	Emitted int `json:"Emitted"`
}

type __octCountAllCheckpointPayload struct {
	Version            int                          `json:"version"`
	Package            string                       `json:"package"`
	Flow               string                       `json:"flow"`
	Fingerprint        string                       `json:"fingerprint"`
	BoardSchema        string                       `json:"board_schema"`
	ConstructionSchema string                       `json:"construction_schema"`
	UtilitySchema      string                       `json:"utility_schema"`
	YieldSchema        string                       `json:"yield_schema"`
	CurrentState       string                       `json:"current_state"`
	Instruction        int                          `json:"instruction"`
	Parameterjobs      []Main_Job                   `json:"parameter_jobs"`
	Board              __octCountAllCheckpointBoard `json:"board"`
	LastYield          Main_Job                     `json:"last_yield"`
	HasYield           bool                         `json:"has_yield"`
}

func (m *CountAll) Checkpoint() (CountAllCheckpoint, error) {
	if m == nil || m.flow == nil {
		return CountAllCheckpoint{}, __octCountAllCheckpointError(CountAllNotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return CountAllCheckpoint{}, __octCountAllCheckpointError(CountAllNotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octCountAllCheckpointPayload{Version: 1, Package: "Main", Flow: "CountAll", Fingerprint: "1ed49b571d1931c956a9c4e988c576f8b7c19fb9c4595687056968658226d7ea", BoardSchema: "Cursor:Int;Emitted:Int;", ConstructionSchema: "jobs:Main.Job[];", UtilitySchema: "", YieldSchema: "Main.Job", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	payload.Parameterjobs = m.flow.jobs
	payload.Board = __octCountAllCheckpointBoard{Cursor: m.flow.board.Cursor, Emitted: m.flow.board.Emitted}
	data, err := json.Marshal(payload)
	if err != nil {
		return CountAllCheckpoint{}, err
	}
	return CountAllCheckpoint{data: data}, nil
}

func RestoreCountAll(checkpoint CountAllCheckpoint) (*CountAll, error) {
	var payload __octCountAllCheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octCountAllCheckpointError(CountAllVersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "CountAll" {
		return nil, __octCountAllCheckpointError(CountAllFlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "1ed49b571d1931c956a9c4e988c576f8b7c19fb9c4595687056968658226d7ea" {
		return nil, __octCountAllCheckpointError(CountAllFingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "Cursor:Int;Emitted:Int;" {
		return nil, __octCountAllCheckpointError(CountAllBoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "jobs:Main.Job[];" {
		return nil, __octCountAllCheckpointError(CountAllConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octCountAllCheckpointError(CountAllUtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Main.Job" {
		return nil, __octCountAllCheckpointError(CountAllYieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octCountAllCheckpointError(CountAllYieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octCountAllStateID(payload.CurrentState)
	if !ok {
		return nil, __octCountAllCheckpointError(CountAllStateMissing, payload.CurrentState)
	}
	if !__octCountAllContinuationValid(stateID, payload.Instruction) {
		return nil, __octCountAllCheckpointError(CountAllContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_CountAll{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	flow.jobs = payload.Parameterjobs
	flow.board.Cursor = payload.Board.Cursor
	flow.board.Emitted = payload.Board.Emitted
	return &CountAll{flow: flow}, nil
}

func __octCountAllStateID(name string) (int, bool) {
	switch name {
	case "Scan":
		return 0, true
	default:
		return 0, false
	}
}
func __octCountAllContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 5
	default:
		return false
	}
}

func fn_Main_IsReady(__oct_user_0 Main_Job) bool {
	var __oct_internal_tmp_0 int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 bool
	_ = __oct_internal_tmp_1
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = __oct_user_0.Status
			__oct_internal_tmp_1 = (__oct_internal_tmp_0 == 1)
			return __oct_internal_tmp_1
		}
	}
}

func fn_Main_JobID(__oct_user_0 Main_Job) int {
	var __oct_internal_tmp_0 int
	_ = __oct_internal_tmp_0
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = __oct_user_0.ID
			return __oct_internal_tmp_0
		}
	}
}

func fn_Main_Main() {
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			return
		}
	}
}

var __octAssertionCount int
