// Code generated by Oct's compiled backend. DO NOT EDIT.
package model

import (
	"encoding/json"
	"fmt"
	"reflect"
)

type __octVoid struct{}

type Main_PositiveAmount = int

func AdmitPositiveAmount(value int) (Main_PositiveAmount, error) {
	admitted := fn_Main___oct_refine_PositiveAmount(value)
	if admitted.IsErr {
		var zero Main_PositiveAmount
		return zero, fmt.Errorf("%s", admitted.Err)
	}
	return admitted.Value, nil
}

type octResult_Int struct {
	Value int
	Err   string
	IsErr bool
}

type octResult_Main_PositiveAmount struct {
	Value Main_PositiveAmount
	Err   string
	IsErr bool
}

type Main_CommandContext struct {
	Kind     Main_CommandKind
	AccountA int
	AccountB int
	Amount   int
	ExistsA  bool
	ExistsB  bool
	BalanceA int
	BalanceB int
	StatusA  Main_AccountStatus
	StatusB  Main_AccountStatus
	VersionA int
	VersionB int
}

type Main_TransitionDecision struct {
	Accepted         bool
	Reason           Main_DecisionReason
	Effect           Main_EffectKind
	AccountA         int
	AccountB         int
	Amount           int
	NewBalanceA      int
	NewBalanceB      int
	NewStatus        Main_AccountStatus
	ExpectedVersionA int
	ExpectedVersionB int
	TransitionCount  int
}

type Main_AccountAgentBoardSnapshot struct {
	TransitionCount int
	Pending         bool
	WasPending      bool
	PendingTarget   int
	PendingAmount   int
}

type Main_CommandKind struct {
	Tag     int
	Payload any
}

const (
	CommandKind_Create_tag        = 0
	CommandKind_Deposit_tag       = 1
	CommandKind_Withdraw_tag      = 2
	CommandKind_Transfer_tag      = 3
	CommandKind_Freeze_tag        = 4
	CommandKind_Unfreeze_tag      = 5
	CommandKind_BeginTransfer_tag = 6
	CommandKind_Confirm_tag       = 7
	CommandKind_Cancel_tag        = 8
)

func NewCommandKindCreate() Main_CommandKind  { return Main_CommandKind{Tag: CommandKind_Create_tag} }
func NewCommandKindDeposit() Main_CommandKind { return Main_CommandKind{Tag: CommandKind_Deposit_tag} }
func NewCommandKindWithdraw() Main_CommandKind {
	return Main_CommandKind{Tag: CommandKind_Withdraw_tag}
}
func NewCommandKindTransfer() Main_CommandKind {
	return Main_CommandKind{Tag: CommandKind_Transfer_tag}
}
func NewCommandKindFreeze() Main_CommandKind { return Main_CommandKind{Tag: CommandKind_Freeze_tag} }
func NewCommandKindUnfreeze() Main_CommandKind {
	return Main_CommandKind{Tag: CommandKind_Unfreeze_tag}
}
func NewCommandKindBeginTransfer() Main_CommandKind {
	return Main_CommandKind{Tag: CommandKind_BeginTransfer_tag}
}
func NewCommandKindConfirm() Main_CommandKind { return Main_CommandKind{Tag: CommandKind_Confirm_tag} }
func NewCommandKindCancel() Main_CommandKind  { return Main_CommandKind{Tag: CommandKind_Cancel_tag} }

type Main_AccountStatus struct {
	Tag     int
	Payload any
}

const (
	AccountStatus_Missing_tag = 0
	AccountStatus_Open_tag    = 1
	AccountStatus_Frozen_tag  = 2
)

func NewAccountStatusMissing() Main_AccountStatus {
	return Main_AccountStatus{Tag: AccountStatus_Missing_tag}
}
func NewAccountStatusOpen() Main_AccountStatus {
	return Main_AccountStatus{Tag: AccountStatus_Open_tag}
}
func NewAccountStatusFrozen() Main_AccountStatus {
	return Main_AccountStatus{Tag: AccountStatus_Frozen_tag}
}

type Main_DecisionReason struct {
	Tag     int
	Payload any
}

const (
	DecisionReason_Applied_tag              = 0
	DecisionReason_AwaitingConfirmation_tag = 1
	DecisionReason_Cancelled_tag            = 2
	DecisionReason_InvalidAmount_tag        = 3
	DecisionReason_AccountMissing_tag       = 4
	DecisionReason_AccountExists_tag        = 5
	DecisionReason_AccountFrozen_tag        = 6
	DecisionReason_InsufficientFunds_tag    = 7
	DecisionReason_InvalidWorkflow_tag      = 8
)

func NewDecisionReasonApplied() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_Applied_tag}
}
func NewDecisionReasonAwaitingConfirmation() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_AwaitingConfirmation_tag}
}
func NewDecisionReasonCancelled() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_Cancelled_tag}
}
func NewDecisionReasonInvalidAmount() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}
}
func NewDecisionReasonAccountMissing() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}
}
func NewDecisionReasonAccountExists() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_AccountExists_tag}
}
func NewDecisionReasonAccountFrozen() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_AccountFrozen_tag}
}
func NewDecisionReasonInsufficientFunds() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_InsufficientFunds_tag}
}
func NewDecisionReasonInvalidWorkflow() Main_DecisionReason {
	return Main_DecisionReason{Tag: DecisionReason_InvalidWorkflow_tag}
}

type Main_EffectKind struct {
	Tag     int
	Payload any
}

const (
	EffectKind_None_tag       = 0
	EffectKind_Create_tag     = 1
	EffectKind_SetBalance_tag = 2
	EffectKind_Transfer_tag   = 3
	EffectKind_SetStatus_tag  = 4
)

func NewEffectKindNone() Main_EffectKind   { return Main_EffectKind{Tag: EffectKind_None_tag} }
func NewEffectKindCreate() Main_EffectKind { return Main_EffectKind{Tag: EffectKind_Create_tag} }
func NewEffectKindSetBalance() Main_EffectKind {
	return Main_EffectKind{Tag: EffectKind_SetBalance_tag}
}
func NewEffectKindTransfer() Main_EffectKind  { return Main_EffectKind{Tag: EffectKind_Transfer_tag} }
func NewEffectKindSetStatus() Main_EffectKind { return Main_EffectKind{Tag: EffectKind_SetStatus_tag} }

type __octFlowInstance_Void interface {
	__octStep(any)
	__octActive() string
	__octComplete() bool
	__octDidYield() bool
	__octYielded() (any, bool)
	__octResult() (__octVoid, bool)
	__octStateHistory() []string
	__octResumeTarget() string
	__octBoardSnapshot() (any, bool)
}

type __octResultFlow_Void struct {
	Value __octVoid
	Err   string
	IsErr bool
}

type __octFlow_Main_AmountAdmission struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	amount       Main_PositiveAmount
	lastYield    int
	hasYield     bool
}

func fn_Main_AmountAdmission() __octFlowInstance_Void {
	__flow := &__octFlow_Main_AmountAdmission{}
	return __flow
}

func (f *__octFlow_Main_AmountAdmission) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Active"
	default:
		return ""
	}
}

func (f *__octFlow_Main_AmountAdmission) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_AmountAdmission) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_AmountAdmission) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_AmountAdmission) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_AmountAdmission) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_AmountAdmission) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_AmountAdmission) __octBoardSnapshot() (any, bool) {
	return nil, false
}

func (f *__octFlow_Main_AmountAdmission) __octStep(__input any) {
	if f.completed {
		panic("runtime error: input supplied after flow completion")
	}
	__typedInput, __ok := __input.(Main_PositiveAmount)
	if !__ok {
		panic("runtime invariant violation: wrong flow turn input type")
	}
	f.amount = __typedInput
	defer func() { var __zero Main_PositiveAmount; f.amount = __zero }()
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.lastYield = f.amount
				f.hasYield = true
				f.instruction++
				return
			case 1:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Active exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Main_AccountAgent struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       __octVoid
	hasResult    bool
	input        Main_CommandContext
	lastYield    Main_TransitionDecision
	hasYield     bool
	owner        int
	board        struct {
		TransitionCount int
		Pending         bool
		WasPending      bool
		PendingTarget   int
		PendingAmount   int
	}
}

func fn_Main_AccountAgent(owner int) __octFlowInstance_Void {
	__flow := &__octFlow_Main_AccountAgent{}
	__flow.owner = owner
	return __flow
}

func (f *__octFlow_Main_AccountAgent) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Active"
	default:
		return ""
	}
}

func (f *__octFlow_Main_AccountAgent) __octComplete() bool { return f.completed }

func (f *__octFlow_Main_AccountAgent) __octDidYield() bool { return f.hasYield }

func (f *__octFlow_Main_AccountAgent) __octYielded() (any, bool) {
	return f.lastYield, f.hasYield
}

func (f *__octFlow_Main_AccountAgent) __octResult() (__octVoid, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Main_AccountAgent) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Main_AccountAgent) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Main_AccountAgent) __octBoardSnapshot() (any, bool) {
	return Main_AccountAgentBoardSnapshot{
		TransitionCount: f.board.TransitionCount,
		Pending:         f.board.Pending,
		WasPending:      f.board.WasPending,
		PendingTarget:   f.board.PendingTarget,
		PendingAmount:   f.board.PendingAmount,
	}, true
}

func (f *__octFlow_Main_AccountAgent) __octStep(__input any) {
	if f.completed {
		panic("runtime error: input supplied after flow completion")
	}
	__typedInput, __ok := __input.(Main_CommandContext)
	if !__ok {
		panic("runtime invariant violation: wrong flow turn input type")
	}
	f.input = __typedInput
	defer func() { var __zero Main_CommandContext; f.input = __zero }()
	f.hasYield = false
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.board.TransitionCount = (f.board.TransitionCount + 1)
				f.instruction++
				continue
			case 1:
				f.board.WasPending = f.board.Pending
				f.instruction++
				continue
			case 2:
				if (f.input.Kind == Main_CommandKind{Tag: CommandKind_BeginTransfer_tag}) && (f.input.Amount > 0) {
					f.board.Pending = true
					f.board.PendingTarget = f.input.AccountB
					f.board.PendingAmount = f.input.Amount
				}
				f.instruction++
				continue
			case 3:
				if (f.input.Kind == Main_CommandKind{Tag: CommandKind_Confirm_tag}) || (f.input.Kind == Main_CommandKind{Tag: CommandKind_Cancel_tag}) {
					f.board.Pending = false
				}
				f.instruction++
				continue
			case 4:
				f.lastYield = fn_Main_Decide(f.input, f.board.TransitionCount, f.board.WasPending, f.board.PendingTarget, f.board.PendingAmount)
				f.hasYield = true
				f.instruction++
				return
			case 5:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Active exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

// AmountAdmission is the generated, typed host facade for the Oct flow Main.AmountAdmission.
type AmountAdmission struct {
	flow *__octFlow_Main_AmountAdmission
}

func NewAmountAdmission() *AmountAdmission {
	return &AmountAdmission{flow: fn_Main_AmountAdmission().(*__octFlow_Main_AmountAdmission)}
}

type AmountAdmissionTurn struct{ machine *AmountAdmission }

func (m *AmountAdmission) Step(input Main_PositiveAmount) (turn AmountAdmissionTurn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	admitted := fn_Main___oct_refine_PositiveAmount(input)
	if admitted.IsErr {
		return turn, fmt.Errorf("%s", admitted.Err)
	}
	m.flow.__octStep(admitted.Value)
	return AmountAdmissionTurn{machine: m}, nil
}

func (t AmountAdmissionTurn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t AmountAdmissionTurn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t AmountAdmissionTurn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t AmountAdmissionTurn) Yielded() (int, error) {
	var zero int
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(int)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *AmountAdmission) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

type AmountAdmissionCheckpointReason string

const (
	AmountAdmissionVersionMismatch      AmountAdmissionCheckpointReason = "CheckpointVersionMismatch"
	AmountAdmissionFlowMismatch         AmountAdmissionCheckpointReason = "FlowMismatch"
	AmountAdmissionFingerprintMismatch  AmountAdmissionCheckpointReason = "FlowFingerprintMismatch"
	AmountAdmissionSchemaMismatch       AmountAdmissionCheckpointReason = "SchemaMismatch"
	AmountAdmissionStateMissing         AmountAdmissionCheckpointReason = "StateMissing"
	AmountAdmissionContinuationInvalid  AmountAdmissionCheckpointReason = "ContinuationPositionInvalid"
	AmountAdmissionBoardSchemaMismatch  AmountAdmissionCheckpointReason = "BoardSchemaMismatch"
	AmountAdmissionConstructionMismatch AmountAdmissionCheckpointReason = "ConstructionParameterMismatch"
	AmountAdmissionUtilitySiteMismatch  AmountAdmissionCheckpointReason = "UtilitySiteMismatch"
	AmountAdmissionYieldSchemaMismatch  AmountAdmissionCheckpointReason = "YieldSchemaMismatch"
	AmountAdmissionNotAtYield           AmountAdmissionCheckpointReason = "NotAtYieldBoundary"
)

type AmountAdmissionCheckpointError struct {
	Reason AmountAdmissionCheckpointReason
	Detail string
}

func (e AmountAdmissionCheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octAmountAdmissionCheckpointError(reason AmountAdmissionCheckpointReason, detail string) error {
	return AmountAdmissionCheckpointError{Reason: reason, Detail: detail}
}

type AmountAdmissionCheckpoint struct{ data []byte }

func (c AmountAdmissionCheckpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseAmountAdmissionCheckpoint(data []byte) (AmountAdmissionCheckpoint, error) {
	var payload __octAmountAdmissionCheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return AmountAdmissionCheckpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return AmountAdmissionCheckpoint{data: out}, nil
}

type __octAmountAdmissionCheckpointPayload struct {
	Version            int    `json:"version"`
	Package            string `json:"package"`
	Flow               string `json:"flow"`
	Fingerprint        string `json:"fingerprint"`
	BoardSchema        string `json:"board_schema"`
	ConstructionSchema string `json:"construction_schema"`
	UtilitySchema      string `json:"utility_schema"`
	YieldSchema        string `json:"yield_schema"`
	CurrentState       string `json:"current_state"`
	Instruction        int    `json:"instruction"`
	LastYield          int    `json:"last_yield"`
	HasYield           bool   `json:"has_yield"`
}

func (m *AmountAdmission) Checkpoint() (AmountAdmissionCheckpoint, error) {
	if m == nil || m.flow == nil {
		return AmountAdmissionCheckpoint{}, __octAmountAdmissionCheckpointError(AmountAdmissionNotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return AmountAdmissionCheckpoint{}, __octAmountAdmissionCheckpointError(AmountAdmissionNotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octAmountAdmissionCheckpointPayload{Version: 1, Package: "Main", Flow: "AmountAdmission", Fingerprint: "cdeb63dc9b2731896f8ba4c941b0bc0edea713088d709a175ce9a87293a986b1", BoardSchema: "", ConstructionSchema: "", UtilitySchema: "", YieldSchema: "Int", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	data, err := json.Marshal(payload)
	if err != nil {
		return AmountAdmissionCheckpoint{}, err
	}
	return AmountAdmissionCheckpoint{data: data}, nil
}

func RestoreAmountAdmission(checkpoint AmountAdmissionCheckpoint) (*AmountAdmission, error) {
	var payload __octAmountAdmissionCheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionVersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "AmountAdmission" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionFlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "cdeb63dc9b2731896f8ba4c941b0bc0edea713088d709a175ce9a87293a986b1" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionFingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionBoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionUtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Int" {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionYieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionYieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octAmountAdmissionStateID(payload.CurrentState)
	if !ok {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionStateMissing, payload.CurrentState)
	}
	if !__octAmountAdmissionContinuationValid(stateID, payload.Instruction) {
		return nil, __octAmountAdmissionCheckpointError(AmountAdmissionContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_AmountAdmission{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	return &AmountAdmission{flow: flow}, nil
}

func __octAmountAdmissionStateID(name string) (int, bool) {
	switch name {
	case "Active":
		return 0, true
	default:
		return 0, false
	}
}
func __octAmountAdmissionContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 2
	default:
		return false
	}
}

// AccountAgent is the generated, typed host facade for the Oct flow Main.AccountAgent.
type AccountAgent struct{ flow *__octFlow_Main_AccountAgent }

func NewAccountAgent(owner int) *AccountAgent {
	return &AccountAgent{flow: fn_Main_AccountAgent(owner).(*__octFlow_Main_AccountAgent)}
}

type AccountAgentTurn struct{ machine *AccountAgent }

func (m *AccountAgent) Step(input Main_CommandContext) (turn AccountAgentTurn, err error) {
	if m == nil || m.flow == nil {
		return turn, fmt.Errorf("flow machine is nil")
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("flow step: %v", recovered)
		}
	}()
	m.flow.__octStep(input)
	return AccountAgentTurn{machine: m}, nil
}

func (t AccountAgentTurn) DidYield() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octDidYield()
}
func (t AccountAgentTurn) Active() string {
	if t.machine == nil || t.machine.flow == nil {
		return ""
	}
	return t.machine.flow.__octActive()
}
func (t AccountAgentTurn) Complete() bool {
	return t.machine != nil && t.machine.flow != nil && t.machine.flow.__octComplete()
}
func (t AccountAgentTurn) Yielded() (Main_TransitionDecision, error) {
	var zero Main_TransitionDecision
	if t.machine == nil || t.machine.flow == nil {
		return zero, fmt.Errorf("flow turn is nil")
	}
	value, ok := t.machine.flow.__octYielded()
	if !ok {
		return zero, fmt.Errorf("last turn did not yield")
	}
	typed, ok := value.(Main_TransitionDecision)
	if !ok {
		return zero, fmt.Errorf("yield type invariant violated")
	}
	return typed, nil
}

func (m *AccountAgent) Result() error {
	if m == nil || m.flow == nil {
		return fmt.Errorf("flow machine is nil")
	}
	_, ok := m.flow.__octResult()
	if !ok {
		return fmt.Errorf("flow has not completed")
	}
	return nil
}

func (m *AccountAgent) Board() (Main_AccountAgentBoardSnapshot, error) {
	var zero Main_AccountAgentBoardSnapshot
	if m == nil || m.flow == nil {
		return zero, fmt.Errorf("flow machine is nil")
	}
	value, ok := m.flow.__octBoardSnapshot()
	if !ok {
		return zero, fmt.Errorf("flow has no board")
	}
	return value.(Main_AccountAgentBoardSnapshot), nil
}

type AccountAgentCheckpointReason string

const (
	AccountAgentVersionMismatch      AccountAgentCheckpointReason = "CheckpointVersionMismatch"
	AccountAgentFlowMismatch         AccountAgentCheckpointReason = "FlowMismatch"
	AccountAgentFingerprintMismatch  AccountAgentCheckpointReason = "FlowFingerprintMismatch"
	AccountAgentSchemaMismatch       AccountAgentCheckpointReason = "SchemaMismatch"
	AccountAgentStateMissing         AccountAgentCheckpointReason = "StateMissing"
	AccountAgentContinuationInvalid  AccountAgentCheckpointReason = "ContinuationPositionInvalid"
	AccountAgentBoardSchemaMismatch  AccountAgentCheckpointReason = "BoardSchemaMismatch"
	AccountAgentConstructionMismatch AccountAgentCheckpointReason = "ConstructionParameterMismatch"
	AccountAgentUtilitySiteMismatch  AccountAgentCheckpointReason = "UtilitySiteMismatch"
	AccountAgentYieldSchemaMismatch  AccountAgentCheckpointReason = "YieldSchemaMismatch"
	AccountAgentNotAtYield           AccountAgentCheckpointReason = "NotAtYieldBoundary"
)

type AccountAgentCheckpointError struct {
	Reason AccountAgentCheckpointReason
	Detail string
}

func (e AccountAgentCheckpointError) Error() string {
	if e.Detail == "" {
		return "flow checkpoint: " + string(e.Reason)
	}
	return "flow checkpoint: " + string(e.Reason) + ": " + e.Detail
}

func __octAccountAgentCheckpointError(reason AccountAgentCheckpointReason, detail string) error {
	return AccountAgentCheckpointError{Reason: reason, Detail: detail}
}

type AccountAgentCheckpoint struct{ data []byte }

func (c AccountAgentCheckpoint) Bytes() []byte {
	out := make([]byte, len(c.data))
	copy(out, c.data)
	return out
}
func ParseAccountAgentCheckpoint(data []byte) (AccountAgentCheckpoint, error) {
	var payload __octAccountAgentCheckpointPayload
	if err := json.Unmarshal(data, &payload); err != nil {
		return AccountAgentCheckpoint{}, err
	}
	out := make([]byte, len(data))
	copy(out, data)
	return AccountAgentCheckpoint{data: out}, nil
}

type __octAccountAgentCheckpointBoard struct {
	TransitionCount int  `json:"TransitionCount"`
	Pending         bool `json:"Pending"`
	WasPending      bool `json:"WasPending"`
	PendingTarget   int  `json:"PendingTarget"`
	PendingAmount   int  `json:"PendingAmount"`
}

type __octAccountAgentCheckpointPayload struct {
	Version            int                              `json:"version"`
	Package            string                           `json:"package"`
	Flow               string                           `json:"flow"`
	Fingerprint        string                           `json:"fingerprint"`
	BoardSchema        string                           `json:"board_schema"`
	ConstructionSchema string                           `json:"construction_schema"`
	UtilitySchema      string                           `json:"utility_schema"`
	YieldSchema        string                           `json:"yield_schema"`
	CurrentState       string                           `json:"current_state"`
	Instruction        int                              `json:"instruction"`
	Parameterowner     int                              `json:"parameter_owner"`
	Board              __octAccountAgentCheckpointBoard `json:"board"`
	LastYield          Main_TransitionDecision          `json:"last_yield"`
	HasYield           bool                             `json:"has_yield"`
}

func (m *AccountAgent) Checkpoint() (AccountAgentCheckpoint, error) {
	if m == nil || m.flow == nil {
		return AccountAgentCheckpoint{}, __octAccountAgentCheckpointError(AccountAgentNotAtYield, "nil flow machine")
	}
	if m.flow.completed || !m.flow.hasYield {
		return AccountAgentCheckpoint{}, __octAccountAgentCheckpointError(AccountAgentNotAtYield, "checkpoint requires the completed turn to have yielded")
	}
	payload := __octAccountAgentCheckpointPayload{Version: 1, Package: "Main", Flow: "AccountAgent", Fingerprint: "36d8d2187661e140f142ab7b43473b3bf7e0bb37f885fb5b7343ffa0f0b987f8", BoardSchema: "TransitionCount:Int;Pending:Bool;WasPending:Bool;PendingTarget:Int;PendingAmount:Int;", ConstructionSchema: "owner:Int;", UtilitySchema: "", YieldSchema: "Main.TransitionDecision", CurrentState: m.flow.__octActive(), Instruction: m.flow.instruction, LastYield: m.flow.lastYield, HasYield: m.flow.hasYield}
	payload.Parameterowner = m.flow.owner
	payload.Board = __octAccountAgentCheckpointBoard{TransitionCount: m.flow.board.TransitionCount, Pending: m.flow.board.Pending, WasPending: m.flow.board.WasPending, PendingTarget: m.flow.board.PendingTarget, PendingAmount: m.flow.board.PendingAmount}
	data, err := json.Marshal(payload)
	if err != nil {
		return AccountAgentCheckpoint{}, err
	}
	return AccountAgentCheckpoint{data: data}, nil
}

func RestoreAccountAgent(checkpoint AccountAgentCheckpoint) (*AccountAgent, error) {
	var payload __octAccountAgentCheckpointPayload
	if err := json.Unmarshal(checkpoint.data, &payload); err != nil {
		return nil, err
	}
	if payload.Version != 1 {
		return nil, __octAccountAgentCheckpointError(AccountAgentVersionMismatch, fmt.Sprintf("version %d", payload.Version))
	}
	if payload.Package != "Main" || payload.Flow != "AccountAgent" {
		return nil, __octAccountAgentCheckpointError(AccountAgentFlowMismatch, payload.Package+"."+payload.Flow)
	}
	if payload.Fingerprint != "36d8d2187661e140f142ab7b43473b3bf7e0bb37f885fb5b7343ffa0f0b987f8" {
		return nil, __octAccountAgentCheckpointError(AccountAgentFingerprintMismatch, "compiled flow changed")
	}
	if payload.BoardSchema != "TransitionCount:Int;Pending:Bool;WasPending:Bool;PendingTarget:Int;PendingAmount:Int;" {
		return nil, __octAccountAgentCheckpointError(AccountAgentBoardSchemaMismatch, "board schema changed")
	}
	if payload.ConstructionSchema != "owner:Int;" {
		return nil, __octAccountAgentCheckpointError(AccountAgentConstructionMismatch, "construction schema changed")
	}
	if payload.UtilitySchema != "" {
		return nil, __octAccountAgentCheckpointError(AccountAgentUtilitySiteMismatch, "utility site schema changed")
	}
	if payload.YieldSchema != "Main.TransitionDecision" {
		return nil, __octAccountAgentCheckpointError(AccountAgentYieldSchemaMismatch, "yield schema changed")
	}
	if !payload.HasYield {
		return nil, __octAccountAgentCheckpointError(AccountAgentYieldSchemaMismatch, "checkpoint is not a yielded machine boundary")
	}
	stateID, ok := __octAccountAgentStateID(payload.CurrentState)
	if !ok {
		return nil, __octAccountAgentCheckpointError(AccountAgentStateMissing, payload.CurrentState)
	}
	if !__octAccountAgentContinuationValid(stateID, payload.Instruction) {
		return nil, __octAccountAgentCheckpointError(AccountAgentContinuationInvalid, fmt.Sprintf("%s[%d]", payload.CurrentState, payload.Instruction))
	}
	flow := &__octFlow_Main_AccountAgent{started: true, currentState: stateID, instruction: payload.Instruction, lastYield: payload.LastYield, hasYield: payload.HasYield}
	flow.owner = payload.Parameterowner
	flow.board.TransitionCount = payload.Board.TransitionCount
	flow.board.Pending = payload.Board.Pending
	flow.board.WasPending = payload.Board.WasPending
	flow.board.PendingTarget = payload.Board.PendingTarget
	flow.board.PendingAmount = payload.Board.PendingAmount
	return &AccountAgent{flow: flow}, nil
}

func __octAccountAgentStateID(name string) (int, bool) {
	switch name {
	case "Active":
		return 0, true
	default:
		return 0, false
	}
}
func __octAccountAgentContinuationValid(state int, instruction int) bool {
	switch state {
	case 0:
		return instruction >= 0 && instruction <= 6
	default:
		return false
	}
}

type __octUtilCandidate[T any] struct {
	Valid bool
	Value T
	Score int
}

type __octUtilitySiteState struct {
	HasCurrent bool
	Current    any
	Score      int
	CommitAge  int
}

func __octUtilSelect[T any](sites map[int]__octUtilitySiteState, siteID int, hysteresis int, minCommit int, candidates []__octUtilCandidate[T], elseValue T) T {
	valid := make([]__octUtilCandidate[T], 0, len(candidates))
	for _, c := range candidates {
		if c.Valid {
			valid = append(valid, c)
		}
	}
	next := __octUtilCandidate[T]{Valid: true, Value: elseValue, Score: 0}
	if len(valid) > 0 {
		next = valid[0]
		for _, c := range valid[1:] {
			if c.Score > next.Score {
				next = c
			}
		}
	}
	site := sites[siteID]
	if site.HasCurrent {
		currentStillValid := false
		for _, c := range valid {
			if reflect.DeepEqual(c.Value, site.Current) {
				currentStillValid = true
				break
			}
		}
		if currentStillValid {
			commitActive := site.CommitAge < minCommit
			hysteresisBlocks := next.Score <= site.Score+hysteresis
			if commitActive || hysteresisBlocks {
				next = __octUtilCandidate[T]{Valid: true, Value: site.Current.(T), Score: site.Score}
			}
		}
	}
	if !site.HasCurrent || !reflect.DeepEqual(site.Current, next.Value) {
		sites[siteID] = __octUtilitySiteState{HasCurrent: true, Current: next.Value, Score: next.Score, CommitAge: 1}
	} else {
		site.Score = next.Score
		site.CommitAge++
		sites[siteID] = site
	}
	return next.Value
}
func fn_Main_Decision(__oct_user_0 Main_CommandContext, __oct_user_1 bool, __oct_user_2 Main_DecisionReason, __oct_user_3 Main_EffectKind, __oct_user_4 int, __oct_user_5 int, __oct_user_6 Main_AccountStatus, __oct_user_7 int) Main_TransitionDecision {
	var __oct_internal_tmp_0 int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_internal_tmp_2 int
	_ = __oct_internal_tmp_2
	var __oct_internal_tmp_3 int
	_ = __oct_internal_tmp_3
	var __oct_internal_tmp_4 int
	_ = __oct_internal_tmp_4
	var __oct_internal_tmp_5 Main_TransitionDecision
	_ = __oct_internal_tmp_5
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = __oct_user_0.AccountA
			__oct_internal_tmp_1 = __oct_user_0.AccountB
			__oct_internal_tmp_2 = __oct_user_0.Amount
			__oct_internal_tmp_3 = __oct_user_0.VersionA
			__oct_internal_tmp_4 = __oct_user_0.VersionB
			__oct_internal_tmp_5 = Main_TransitionDecision{Accepted: __oct_user_1, Reason: __oct_user_2, Effect: __oct_user_3, AccountA: __oct_internal_tmp_0, AccountB: __oct_internal_tmp_1, Amount: __oct_internal_tmp_2, NewBalanceA: __oct_user_4, NewBalanceB: __oct_user_5, NewStatus: __oct_user_6, ExpectedVersionA: __oct_internal_tmp_3, ExpectedVersionB: __oct_internal_tmp_4, TransitionCount: __oct_user_7}
			return __oct_internal_tmp_5
		}
	}
}

func fn_Main_DecideCode(__oct_user_0 Main_CommandContext, __oct_user_1 bool, __oct_user_2 int, __oct_user_3 int) int {
	var __oct_internal_tmp_0 Main_CommandKind
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 bool
	_ = __oct_internal_tmp_1
	var __oct_internal_tmp_10 bool
	_ = __oct_internal_tmp_10
	var __oct_internal_tmp_100 bool
	_ = __oct_internal_tmp_100
	var __oct_internal_tmp_101 bool
	_ = __oct_internal_tmp_101
	var __oct_internal_tmp_102 Main_CommandKind
	_ = __oct_internal_tmp_102
	var __oct_internal_tmp_103 bool
	_ = __oct_internal_tmp_103
	var __oct_internal_tmp_104 Main_CommandKind
	_ = __oct_internal_tmp_104
	var __oct_internal_tmp_105 bool
	_ = __oct_internal_tmp_105
	var __oct_internal_tmp_106 bool
	_ = __oct_internal_tmp_106
	var __oct_internal_tmp_107 bool
	_ = __oct_internal_tmp_107
	var __oct_internal_tmp_108 bool
	_ = __oct_internal_tmp_108
	var __oct_internal_tmp_109 Main_CommandKind
	_ = __oct_internal_tmp_109
	var __oct_internal_tmp_11 Main_CommandKind
	_ = __oct_internal_tmp_11
	var __oct_internal_tmp_110 bool
	_ = __oct_internal_tmp_110
	var __oct_internal_tmp_111 Main_CommandKind
	_ = __oct_internal_tmp_111
	var __oct_internal_tmp_112 bool
	_ = __oct_internal_tmp_112
	var __oct_internal_tmp_113 bool
	_ = __oct_internal_tmp_113
	var __oct_internal_tmp_114 int
	_ = __oct_internal_tmp_114
	var __oct_internal_tmp_115 bool
	_ = __oct_internal_tmp_115
	var __oct_internal_tmp_116 Main_CommandKind
	_ = __oct_internal_tmp_116
	var __oct_internal_tmp_117 bool
	_ = __oct_internal_tmp_117
	var __oct_internal_tmp_118 Main_CommandKind
	_ = __oct_internal_tmp_118
	var __oct_internal_tmp_119 bool
	_ = __oct_internal_tmp_119
	var __oct_internal_tmp_12 bool
	_ = __oct_internal_tmp_12
	var __oct_internal_tmp_13 bool
	_ = __oct_internal_tmp_13
	var __oct_internal_tmp_14 int
	_ = __oct_internal_tmp_14
	var __oct_internal_tmp_15 bool
	_ = __oct_internal_tmp_15
	var __oct_internal_tmp_16 Main_CommandKind
	_ = __oct_internal_tmp_16
	var __oct_internal_tmp_17 bool
	_ = __oct_internal_tmp_17
	var __oct_internal_tmp_18 bool
	_ = __oct_internal_tmp_18
	var __oct_internal_tmp_19 bool
	_ = __oct_internal_tmp_19
	var __oct_internal_tmp_2 bool
	_ = __oct_internal_tmp_2
	var __oct_internal_tmp_20 bool
	_ = __oct_internal_tmp_20
	var __oct_internal_tmp_21 Main_CommandKind
	_ = __oct_internal_tmp_21
	var __oct_internal_tmp_22 bool
	_ = __oct_internal_tmp_22
	var __oct_internal_tmp_23 Main_CommandKind
	_ = __oct_internal_tmp_23
	var __oct_internal_tmp_24 bool
	_ = __oct_internal_tmp_24
	var __oct_internal_tmp_25 bool
	_ = __oct_internal_tmp_25
	var __oct_internal_tmp_26 int
	_ = __oct_internal_tmp_26
	var __oct_internal_tmp_27 bool
	_ = __oct_internal_tmp_27
	var __oct_internal_tmp_28 Main_CommandKind
	_ = __oct_internal_tmp_28
	var __oct_internal_tmp_29 bool
	_ = __oct_internal_tmp_29
	var __oct_internal_tmp_3 bool
	_ = __oct_internal_tmp_3
	var __oct_internal_tmp_30 bool
	_ = __oct_internal_tmp_30
	var __oct_internal_tmp_31 bool
	_ = __oct_internal_tmp_31
	var __oct_internal_tmp_32 bool
	_ = __oct_internal_tmp_32
	var __oct_internal_tmp_33 Main_CommandKind
	_ = __oct_internal_tmp_33
	var __oct_internal_tmp_34 bool
	_ = __oct_internal_tmp_34
	var __oct_internal_tmp_35 bool
	_ = __oct_internal_tmp_35
	var __oct_internal_tmp_36 Main_AccountStatus
	_ = __oct_internal_tmp_36
	var __oct_internal_tmp_37 bool
	_ = __oct_internal_tmp_37
	var __oct_internal_tmp_38 Main_CommandKind
	_ = __oct_internal_tmp_38
	var __oct_internal_tmp_39 bool
	_ = __oct_internal_tmp_39
	var __oct_internal_tmp_4 Main_CommandKind
	_ = __oct_internal_tmp_4
	var __oct_internal_tmp_40 bool
	_ = __oct_internal_tmp_40
	var __oct_internal_tmp_41 int
	_ = __oct_internal_tmp_41
	var __oct_internal_tmp_42 int
	_ = __oct_internal_tmp_42
	var __oct_internal_tmp_43 bool
	_ = __oct_internal_tmp_43
	var __oct_internal_tmp_44 Main_CommandKind
	_ = __oct_internal_tmp_44
	var __oct_internal_tmp_45 bool
	_ = __oct_internal_tmp_45
	var __oct_internal_tmp_46 Main_CommandKind
	_ = __oct_internal_tmp_46
	var __oct_internal_tmp_47 bool
	_ = __oct_internal_tmp_47
	var __oct_internal_tmp_48 bool
	_ = __oct_internal_tmp_48
	var __oct_internal_tmp_49 bool
	_ = __oct_internal_tmp_49
	var __oct_internal_tmp_5 bool
	_ = __oct_internal_tmp_5
	var __oct_internal_tmp_50 bool
	_ = __oct_internal_tmp_50
	var __oct_internal_tmp_51 int
	_ = __oct_internal_tmp_51
	var __oct_internal_tmp_52 bool
	_ = __oct_internal_tmp_52
	var __oct_internal_tmp_53 bool
	_ = __oct_internal_tmp_53
	var __oct_internal_tmp_54 int
	_ = __oct_internal_tmp_54
	var __oct_internal_tmp_55 bool
	_ = __oct_internal_tmp_55
	var __oct_internal_tmp_56 Main_CommandKind
	_ = __oct_internal_tmp_56
	var __oct_internal_tmp_57 bool
	_ = __oct_internal_tmp_57
	var __oct_internal_tmp_58 bool
	_ = __oct_internal_tmp_58
	var __oct_internal_tmp_59 Main_CommandKind
	_ = __oct_internal_tmp_59
	var __oct_internal_tmp_6 bool
	_ = __oct_internal_tmp_6
	var __oct_internal_tmp_60 bool
	_ = __oct_internal_tmp_60
	var __oct_internal_tmp_61 bool
	_ = __oct_internal_tmp_61
	var __oct_internal_tmp_62 int
	_ = __oct_internal_tmp_62
	var __oct_internal_tmp_63 bool
	_ = __oct_internal_tmp_63
	var __oct_internal_tmp_64 Main_CommandKind
	_ = __oct_internal_tmp_64
	var __oct_internal_tmp_65 bool
	_ = __oct_internal_tmp_65
	var __oct_internal_tmp_66 bool
	_ = __oct_internal_tmp_66
	var __oct_internal_tmp_67 Main_CommandKind
	_ = __oct_internal_tmp_67
	var __oct_internal_tmp_68 bool
	_ = __oct_internal_tmp_68
	var __oct_internal_tmp_69 bool
	_ = __oct_internal_tmp_69
	var __oct_internal_tmp_7 int
	_ = __oct_internal_tmp_7
	var __oct_internal_tmp_70 bool
	_ = __oct_internal_tmp_70
	var __oct_internal_tmp_71 bool
	_ = __oct_internal_tmp_71
	var __oct_internal_tmp_72 bool
	_ = __oct_internal_tmp_72
	var __oct_internal_tmp_73 bool
	_ = __oct_internal_tmp_73
	var __oct_internal_tmp_74 bool
	_ = __oct_internal_tmp_74
	var __oct_internal_tmp_75 Main_CommandKind
	_ = __oct_internal_tmp_75
	var __oct_internal_tmp_76 bool
	_ = __oct_internal_tmp_76
	var __oct_internal_tmp_77 bool
	_ = __oct_internal_tmp_77
	var __oct_internal_tmp_78 Main_CommandKind
	_ = __oct_internal_tmp_78
	var __oct_internal_tmp_79 bool
	_ = __oct_internal_tmp_79
	var __oct_internal_tmp_8 bool
	_ = __oct_internal_tmp_8
	var __oct_internal_tmp_80 bool
	_ = __oct_internal_tmp_80
	var __oct_internal_tmp_81 Main_AccountStatus
	_ = __oct_internal_tmp_81
	var __oct_internal_tmp_82 bool
	_ = __oct_internal_tmp_82
	var __oct_internal_tmp_83 Main_CommandKind
	_ = __oct_internal_tmp_83
	var __oct_internal_tmp_84 bool
	_ = __oct_internal_tmp_84
	var __oct_internal_tmp_85 bool
	_ = __oct_internal_tmp_85
	var __oct_internal_tmp_86 Main_CommandKind
	_ = __oct_internal_tmp_86
	var __oct_internal_tmp_87 bool
	_ = __oct_internal_tmp_87
	var __oct_internal_tmp_88 bool
	_ = __oct_internal_tmp_88
	var __oct_internal_tmp_89 int
	_ = __oct_internal_tmp_89
	var __oct_internal_tmp_9 Main_CommandKind
	_ = __oct_internal_tmp_9
	var __oct_internal_tmp_90 int
	_ = __oct_internal_tmp_90
	var __oct_internal_tmp_91 bool
	_ = __oct_internal_tmp_91
	var __oct_internal_tmp_92 Main_CommandKind
	_ = __oct_internal_tmp_92
	var __oct_internal_tmp_93 bool
	_ = __oct_internal_tmp_93
	var __oct_internal_tmp_94 bool
	_ = __oct_internal_tmp_94
	var __oct_internal_tmp_95 Main_CommandKind
	_ = __oct_internal_tmp_95
	var __oct_internal_tmp_96 bool
	_ = __oct_internal_tmp_96
	var __oct_internal_tmp_97 Main_CommandKind
	_ = __oct_internal_tmp_97
	var __oct_internal_tmp_98 bool
	_ = __oct_internal_tmp_98
	var __oct_internal_tmp_99 bool
	_ = __oct_internal_tmp_99
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = __oct_user_0.Kind
			__oct_internal_tmp_1 = (__oct_internal_tmp_0 == Main_CommandKind{Tag: CommandKind_Create_tag})
			__oct_internal_tmp_2 = false
			if __oct_internal_tmp_1 {
				__oct_internal_pc = 1
			} else {
				__oct_internal_pc = 2
			}
			continue
		case 1:
			__oct_internal_tmp_3 = __oct_user_0.ExistsA
			__oct_internal_tmp_2 = __oct_internal_tmp_3
			__oct_internal_pc = 2
			continue
		case 2:
			__oct_internal_tmp_4 = __oct_user_0.Kind
			__oct_internal_tmp_5 = (__oct_internal_tmp_4 == Main_CommandKind{Tag: CommandKind_Create_tag})
			__oct_internal_tmp_6 = false
			if __oct_internal_tmp_5 {
				__oct_internal_pc = 3
			} else {
				__oct_internal_pc = 4
			}
			continue
		case 3:
			__oct_internal_tmp_7 = __oct_user_0.Amount
			__oct_internal_tmp_8 = (__oct_internal_tmp_7 < 0)
			__oct_internal_tmp_6 = __oct_internal_tmp_8
			__oct_internal_pc = 4
			continue
		case 4:
			__oct_internal_tmp_9 = __oct_user_0.Kind
			__oct_internal_tmp_10 = (__oct_internal_tmp_9 == Main_CommandKind{Tag: CommandKind_Create_tag})
			__oct_internal_tmp_11 = __oct_user_0.Kind
			__oct_internal_tmp_12 = (__oct_internal_tmp_11 == Main_CommandKind{Tag: CommandKind_Deposit_tag})
			__oct_internal_tmp_13 = false
			if __oct_internal_tmp_12 {
				__oct_internal_pc = 5
			} else {
				__oct_internal_pc = 6
			}
			continue
		case 5:
			__oct_internal_tmp_14 = __oct_user_0.Amount
			__oct_internal_tmp_15 = (__oct_internal_tmp_14 <= 0)
			__oct_internal_tmp_13 = __oct_internal_tmp_15
			__oct_internal_pc = 6
			continue
		case 6:
			__oct_internal_tmp_16 = __oct_user_0.Kind
			__oct_internal_tmp_17 = (__oct_internal_tmp_16 == Main_CommandKind{Tag: CommandKind_Deposit_tag})
			__oct_internal_tmp_18 = false
			if __oct_internal_tmp_17 {
				__oct_internal_pc = 7
			} else {
				__oct_internal_pc = 8
			}
			continue
		case 7:
			__oct_internal_tmp_19 = __oct_user_0.ExistsA
			__oct_internal_tmp_20 = (!__oct_internal_tmp_19)
			__oct_internal_tmp_18 = __oct_internal_tmp_20
			__oct_internal_pc = 8
			continue
		case 8:
			__oct_internal_tmp_21 = __oct_user_0.Kind
			__oct_internal_tmp_22 = (__oct_internal_tmp_21 == Main_CommandKind{Tag: CommandKind_Deposit_tag})
			__oct_internal_tmp_23 = __oct_user_0.Kind
			__oct_internal_tmp_24 = (__oct_internal_tmp_23 == Main_CommandKind{Tag: CommandKind_Withdraw_tag})
			__oct_internal_tmp_25 = false
			if __oct_internal_tmp_24 {
				__oct_internal_pc = 9
			} else {
				__oct_internal_pc = 10
			}
			continue
		case 9:
			__oct_internal_tmp_26 = __oct_user_0.Amount
			__oct_internal_tmp_27 = (__oct_internal_tmp_26 <= 0)
			__oct_internal_tmp_25 = __oct_internal_tmp_27
			__oct_internal_pc = 10
			continue
		case 10:
			__oct_internal_tmp_28 = __oct_user_0.Kind
			__oct_internal_tmp_29 = (__oct_internal_tmp_28 == Main_CommandKind{Tag: CommandKind_Withdraw_tag})
			__oct_internal_tmp_30 = false
			if __oct_internal_tmp_29 {
				__oct_internal_pc = 11
			} else {
				__oct_internal_pc = 12
			}
			continue
		case 11:
			__oct_internal_tmp_31 = __oct_user_0.ExistsA
			__oct_internal_tmp_32 = (!__oct_internal_tmp_31)
			__oct_internal_tmp_30 = __oct_internal_tmp_32
			__oct_internal_pc = 12
			continue
		case 12:
			__oct_internal_tmp_33 = __oct_user_0.Kind
			__oct_internal_tmp_34 = (__oct_internal_tmp_33 == Main_CommandKind{Tag: CommandKind_Withdraw_tag})
			__oct_internal_tmp_35 = false
			if __oct_internal_tmp_34 {
				__oct_internal_pc = 13
			} else {
				__oct_internal_pc = 14
			}
			continue
		case 13:
			__oct_internal_tmp_36 = __oct_user_0.StatusA
			__oct_internal_tmp_37 = (__oct_internal_tmp_36 == Main_AccountStatus{Tag: AccountStatus_Frozen_tag})
			__oct_internal_tmp_35 = __oct_internal_tmp_37
			__oct_internal_pc = 14
			continue
		case 14:
			__oct_internal_tmp_38 = __oct_user_0.Kind
			__oct_internal_tmp_39 = (__oct_internal_tmp_38 == Main_CommandKind{Tag: CommandKind_Withdraw_tag})
			__oct_internal_tmp_40 = false
			if __oct_internal_tmp_39 {
				__oct_internal_pc = 15
			} else {
				__oct_internal_pc = 16
			}
			continue
		case 15:
			__oct_internal_tmp_41 = __oct_user_0.BalanceA
			__oct_internal_tmp_42 = __oct_user_0.Amount
			__oct_internal_tmp_43 = (__oct_internal_tmp_41 < __oct_internal_tmp_42)
			__oct_internal_tmp_40 = __oct_internal_tmp_43
			__oct_internal_pc = 16
			continue
		case 16:
			__oct_internal_tmp_44 = __oct_user_0.Kind
			__oct_internal_tmp_45 = (__oct_internal_tmp_44 == Main_CommandKind{Tag: CommandKind_Withdraw_tag})
			__oct_internal_tmp_46 = __oct_user_0.Kind
			__oct_internal_tmp_47 = (__oct_internal_tmp_46 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_48 = false
			if __oct_internal_tmp_47 {
				__oct_internal_pc = 17
			} else {
				__oct_internal_pc = 18
			}
			continue
		case 17:
			__oct_internal_tmp_49 = (!__oct_user_1)
			__oct_internal_tmp_50 = true
			if __oct_internal_tmp_49 {
				__oct_internal_pc = 20
			} else {
				__oct_internal_pc = 19
			}
			continue
		case 18:
			__oct_internal_tmp_56 = __oct_user_0.Kind
			__oct_internal_tmp_57 = (__oct_internal_tmp_56 == Main_CommandKind{Tag: CommandKind_Transfer_tag})
			__oct_internal_tmp_58 = true
			if __oct_internal_tmp_57 {
				__oct_internal_pc = 24
			} else {
				__oct_internal_pc = 23
			}
			continue
		case 19:
			__oct_internal_tmp_51 = __oct_user_0.AccountB
			__oct_internal_tmp_52 = (__oct_user_2 != __oct_internal_tmp_51)
			__oct_internal_tmp_50 = __oct_internal_tmp_52
			__oct_internal_pc = 20
			continue
		case 20:
			__oct_internal_tmp_53 = true
			if __oct_internal_tmp_50 {
				__oct_internal_pc = 22
			} else {
				__oct_internal_pc = 21
			}
			continue
		case 21:
			__oct_internal_tmp_54 = __oct_user_0.Amount
			__oct_internal_tmp_55 = (__oct_user_3 != __oct_internal_tmp_54)
			__oct_internal_tmp_53 = __oct_internal_tmp_55
			__oct_internal_pc = 22
			continue
		case 22:
			__oct_internal_tmp_48 = __oct_internal_tmp_53
			__oct_internal_pc = 18
			continue
		case 23:
			__oct_internal_tmp_59 = __oct_user_0.Kind
			__oct_internal_tmp_60 = (__oct_internal_tmp_59 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_58 = __oct_internal_tmp_60
			__oct_internal_pc = 24
			continue
		case 24:
			__oct_internal_tmp_61 = false
			if __oct_internal_tmp_58 {
				__oct_internal_pc = 25
			} else {
				__oct_internal_pc = 26
			}
			continue
		case 25:
			__oct_internal_tmp_62 = __oct_user_0.Amount
			__oct_internal_tmp_63 = (__oct_internal_tmp_62 <= 0)
			__oct_internal_tmp_61 = __oct_internal_tmp_63
			__oct_internal_pc = 26
			continue
		case 26:
			__oct_internal_tmp_64 = __oct_user_0.Kind
			__oct_internal_tmp_65 = (__oct_internal_tmp_64 == Main_CommandKind{Tag: CommandKind_Transfer_tag})
			__oct_internal_tmp_66 = true
			if __oct_internal_tmp_65 {
				__oct_internal_pc = 28
			} else {
				__oct_internal_pc = 27
			}
			continue
		case 27:
			__oct_internal_tmp_67 = __oct_user_0.Kind
			__oct_internal_tmp_68 = (__oct_internal_tmp_67 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_66 = __oct_internal_tmp_68
			__oct_internal_pc = 28
			continue
		case 28:
			__oct_internal_tmp_69 = false
			if __oct_internal_tmp_66 {
				__oct_internal_pc = 29
			} else {
				__oct_internal_pc = 30
			}
			continue
		case 29:
			__oct_internal_tmp_70 = __oct_user_0.ExistsA
			__oct_internal_tmp_71 = (!__oct_internal_tmp_70)
			__oct_internal_tmp_72 = true
			if __oct_internal_tmp_71 {
				__oct_internal_pc = 32
			} else {
				__oct_internal_pc = 31
			}
			continue
		case 30:
			__oct_internal_tmp_75 = __oct_user_0.Kind
			__oct_internal_tmp_76 = (__oct_internal_tmp_75 == Main_CommandKind{Tag: CommandKind_Transfer_tag})
			__oct_internal_tmp_77 = true
			if __oct_internal_tmp_76 {
				__oct_internal_pc = 34
			} else {
				__oct_internal_pc = 33
			}
			continue
		case 31:
			__oct_internal_tmp_73 = __oct_user_0.ExistsB
			__oct_internal_tmp_74 = (!__oct_internal_tmp_73)
			__oct_internal_tmp_72 = __oct_internal_tmp_74
			__oct_internal_pc = 32
			continue
		case 32:
			__oct_internal_tmp_69 = __oct_internal_tmp_72
			__oct_internal_pc = 30
			continue
		case 33:
			__oct_internal_tmp_78 = __oct_user_0.Kind
			__oct_internal_tmp_79 = (__oct_internal_tmp_78 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_77 = __oct_internal_tmp_79
			__oct_internal_pc = 34
			continue
		case 34:
			__oct_internal_tmp_80 = false
			if __oct_internal_tmp_77 {
				__oct_internal_pc = 35
			} else {
				__oct_internal_pc = 36
			}
			continue
		case 35:
			__oct_internal_tmp_81 = __oct_user_0.StatusA
			__oct_internal_tmp_82 = (__oct_internal_tmp_81 == Main_AccountStatus{Tag: AccountStatus_Frozen_tag})
			__oct_internal_tmp_80 = __oct_internal_tmp_82
			__oct_internal_pc = 36
			continue
		case 36:
			__oct_internal_tmp_83 = __oct_user_0.Kind
			__oct_internal_tmp_84 = (__oct_internal_tmp_83 == Main_CommandKind{Tag: CommandKind_Transfer_tag})
			__oct_internal_tmp_85 = true
			if __oct_internal_tmp_84 {
				__oct_internal_pc = 38
			} else {
				__oct_internal_pc = 37
			}
			continue
		case 37:
			__oct_internal_tmp_86 = __oct_user_0.Kind
			__oct_internal_tmp_87 = (__oct_internal_tmp_86 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_85 = __oct_internal_tmp_87
			__oct_internal_pc = 38
			continue
		case 38:
			__oct_internal_tmp_88 = false
			if __oct_internal_tmp_85 {
				__oct_internal_pc = 39
			} else {
				__oct_internal_pc = 40
			}
			continue
		case 39:
			__oct_internal_tmp_89 = __oct_user_0.BalanceA
			__oct_internal_tmp_90 = __oct_user_0.Amount
			__oct_internal_tmp_91 = (__oct_internal_tmp_89 < __oct_internal_tmp_90)
			__oct_internal_tmp_88 = __oct_internal_tmp_91
			__oct_internal_pc = 40
			continue
		case 40:
			__oct_internal_tmp_92 = __oct_user_0.Kind
			__oct_internal_tmp_93 = (__oct_internal_tmp_92 == Main_CommandKind{Tag: CommandKind_Transfer_tag})
			__oct_internal_tmp_94 = true
			if __oct_internal_tmp_93 {
				__oct_internal_pc = 42
			} else {
				__oct_internal_pc = 41
			}
			continue
		case 41:
			__oct_internal_tmp_95 = __oct_user_0.Kind
			__oct_internal_tmp_96 = (__oct_internal_tmp_95 == Main_CommandKind{Tag: CommandKind_Confirm_tag})
			__oct_internal_tmp_94 = __oct_internal_tmp_96
			__oct_internal_pc = 42
			continue
		case 42:
			__oct_internal_tmp_97 = __oct_user_0.Kind
			__oct_internal_tmp_98 = (__oct_internal_tmp_97 == Main_CommandKind{Tag: CommandKind_Freeze_tag})
			__oct_internal_tmp_99 = false
			if __oct_internal_tmp_98 {
				__oct_internal_pc = 43
			} else {
				__oct_internal_pc = 44
			}
			continue
		case 43:
			__oct_internal_tmp_100 = __oct_user_0.ExistsA
			__oct_internal_tmp_101 = (!__oct_internal_tmp_100)
			__oct_internal_tmp_99 = __oct_internal_tmp_101
			__oct_internal_pc = 44
			continue
		case 44:
			__oct_internal_tmp_102 = __oct_user_0.Kind
			__oct_internal_tmp_103 = (__oct_internal_tmp_102 == Main_CommandKind{Tag: CommandKind_Freeze_tag})
			__oct_internal_tmp_104 = __oct_user_0.Kind
			__oct_internal_tmp_105 = (__oct_internal_tmp_104 == Main_CommandKind{Tag: CommandKind_Unfreeze_tag})
			__oct_internal_tmp_106 = false
			if __oct_internal_tmp_105 {
				__oct_internal_pc = 45
			} else {
				__oct_internal_pc = 46
			}
			continue
		case 45:
			__oct_internal_tmp_107 = __oct_user_0.ExistsA
			__oct_internal_tmp_108 = (!__oct_internal_tmp_107)
			__oct_internal_tmp_106 = __oct_internal_tmp_108
			__oct_internal_pc = 46
			continue
		case 46:
			__oct_internal_tmp_109 = __oct_user_0.Kind
			__oct_internal_tmp_110 = (__oct_internal_tmp_109 == Main_CommandKind{Tag: CommandKind_Unfreeze_tag})
			__oct_internal_tmp_111 = __oct_user_0.Kind
			__oct_internal_tmp_112 = (__oct_internal_tmp_111 == Main_CommandKind{Tag: CommandKind_BeginTransfer_tag})
			__oct_internal_tmp_113 = false
			if __oct_internal_tmp_112 {
				__oct_internal_pc = 47
			} else {
				__oct_internal_pc = 48
			}
			continue
		case 47:
			__oct_internal_tmp_114 = __oct_user_0.Amount
			__oct_internal_tmp_115 = (__oct_internal_tmp_114 <= 0)
			__oct_internal_tmp_113 = __oct_internal_tmp_115
			__oct_internal_pc = 48
			continue
		case 48:
			__oct_internal_tmp_116 = __oct_user_0.Kind
			__oct_internal_tmp_117 = (__oct_internal_tmp_116 == Main_CommandKind{Tag: CommandKind_BeginTransfer_tag})
			__oct_internal_tmp_118 = __oct_user_0.Kind
			__oct_internal_tmp_119 = (__oct_internal_tmp_118 == Main_CommandKind{Tag: CommandKind_Cancel_tag})
			return __octUtilSelect[int](map[int]__octUtilitySiteState{}, 0, 0, 0, []__octUtilCandidate[int]{{Valid: __oct_internal_tmp_2, Value: 1, Score: 100}, {Valid: __oct_internal_tmp_6, Value: 2, Score: 90}, {Valid: __oct_internal_tmp_10, Value: 3, Score: 10}, {Valid: __oct_internal_tmp_13, Value: 4, Score: 100}, {Valid: __oct_internal_tmp_18, Value: 5, Score: 90}, {Valid: __oct_internal_tmp_22, Value: 6, Score: 10}, {Valid: __oct_internal_tmp_25, Value: 7, Score: 100}, {Valid: __oct_internal_tmp_30, Value: 8, Score: 90}, {Valid: __oct_internal_tmp_35, Value: 9, Score: 80}, {Valid: __oct_internal_tmp_40, Value: 10, Score: 70}, {Valid: __oct_internal_tmp_45, Value: 11, Score: 10}, {Valid: __oct_internal_tmp_48, Value: 12, Score: 110}, {Valid: __oct_internal_tmp_61, Value: 13, Score: 100}, {Valid: __oct_internal_tmp_69, Value: 14, Score: 90}, {Valid: __oct_internal_tmp_80, Value: 15, Score: 80}, {Valid: __oct_internal_tmp_88, Value: 16, Score: 70}, {Valid: __oct_internal_tmp_94, Value: 17, Score: 10}, {Valid: __oct_internal_tmp_99, Value: 18, Score: 100}, {Valid: __oct_internal_tmp_103, Value: 19, Score: 10}, {Valid: __oct_internal_tmp_106, Value: 20, Score: 100}, {Valid: __oct_internal_tmp_110, Value: 21, Score: 10}, {Valid: __oct_internal_tmp_113, Value: 22, Score: 100}, {Valid: __oct_internal_tmp_117, Value: 23, Score: 10}, {Valid: __oct_internal_tmp_119, Value: 24, Score: 10}}, 0)
		}
	}
}

func fn_Main_Decide(__oct_user_0 Main_CommandContext, __oct_user_1 int, __oct_user_2 bool, __oct_user_3 int, __oct_user_4 int) Main_TransitionDecision {
	var __oct_internal_tmp_0 int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 bool
	_ = __oct_internal_tmp_1
	var __oct_internal_tmp_10 Main_AccountStatus
	_ = __oct_internal_tmp_10
	var __oct_internal_tmp_100 int
	_ = __oct_internal_tmp_100
	var __oct_internal_tmp_101 int
	_ = __oct_internal_tmp_101
	var __oct_internal_tmp_102 Main_TransitionDecision
	_ = __oct_internal_tmp_102
	var __oct_internal_tmp_103 bool
	_ = __oct_internal_tmp_103
	var __oct_internal_tmp_104 int
	_ = __oct_internal_tmp_104
	var __oct_internal_tmp_105 int
	_ = __oct_internal_tmp_105
	var __oct_internal_tmp_106 Main_AccountStatus
	_ = __oct_internal_tmp_106
	var __oct_internal_tmp_107 Main_TransitionDecision
	_ = __oct_internal_tmp_107
	var __oct_internal_tmp_108 bool
	_ = __oct_internal_tmp_108
	var __oct_internal_tmp_109 int
	_ = __oct_internal_tmp_109
	var __oct_internal_tmp_11 Main_TransitionDecision
	_ = __oct_internal_tmp_11
	var __oct_internal_tmp_110 int
	_ = __oct_internal_tmp_110
	var __oct_internal_tmp_111 Main_TransitionDecision
	_ = __oct_internal_tmp_111
	var __oct_internal_tmp_112 bool
	_ = __oct_internal_tmp_112
	var __oct_internal_tmp_113 int
	_ = __oct_internal_tmp_113
	var __oct_internal_tmp_114 int
	_ = __oct_internal_tmp_114
	var __oct_internal_tmp_115 Main_AccountStatus
	_ = __oct_internal_tmp_115
	var __oct_internal_tmp_116 Main_TransitionDecision
	_ = __oct_internal_tmp_116
	var __oct_internal_tmp_117 bool
	_ = __oct_internal_tmp_117
	var __oct_internal_tmp_118 int
	_ = __oct_internal_tmp_118
	var __oct_internal_tmp_119 int
	_ = __oct_internal_tmp_119
	var __oct_internal_tmp_12 bool
	_ = __oct_internal_tmp_12
	var __oct_internal_tmp_120 Main_AccountStatus
	_ = __oct_internal_tmp_120
	var __oct_internal_tmp_121 Main_TransitionDecision
	_ = __oct_internal_tmp_121
	var __oct_internal_tmp_122 bool
	_ = __oct_internal_tmp_122
	var __oct_internal_tmp_123 int
	_ = __oct_internal_tmp_123
	var __oct_internal_tmp_124 int
	_ = __oct_internal_tmp_124
	var __oct_internal_tmp_125 Main_AccountStatus
	_ = __oct_internal_tmp_125
	var __oct_internal_tmp_126 Main_TransitionDecision
	_ = __oct_internal_tmp_126
	var __oct_internal_tmp_127 int
	_ = __oct_internal_tmp_127
	var __oct_internal_tmp_128 int
	_ = __oct_internal_tmp_128
	var __oct_internal_tmp_129 Main_AccountStatus
	_ = __oct_internal_tmp_129
	var __oct_internal_tmp_13 int
	_ = __oct_internal_tmp_13
	var __oct_internal_tmp_130 Main_TransitionDecision
	_ = __oct_internal_tmp_130
	var __oct_internal_tmp_14 int
	_ = __oct_internal_tmp_14
	var __oct_internal_tmp_15 Main_TransitionDecision
	_ = __oct_internal_tmp_15
	var __oct_internal_tmp_16 bool
	_ = __oct_internal_tmp_16
	var __oct_internal_tmp_17 int
	_ = __oct_internal_tmp_17
	var __oct_internal_tmp_18 int
	_ = __oct_internal_tmp_18
	var __oct_internal_tmp_19 Main_AccountStatus
	_ = __oct_internal_tmp_19
	var __oct_internal_tmp_2 int
	_ = __oct_internal_tmp_2
	var __oct_internal_tmp_20 Main_TransitionDecision
	_ = __oct_internal_tmp_20
	var __oct_internal_tmp_21 bool
	_ = __oct_internal_tmp_21
	var __oct_internal_tmp_22 int
	_ = __oct_internal_tmp_22
	var __oct_internal_tmp_23 int
	_ = __oct_internal_tmp_23
	var __oct_internal_tmp_24 Main_AccountStatus
	_ = __oct_internal_tmp_24
	var __oct_internal_tmp_25 Main_TransitionDecision
	_ = __oct_internal_tmp_25
	var __oct_internal_tmp_26 bool
	_ = __oct_internal_tmp_26
	var __oct_internal_tmp_27 int
	_ = __oct_internal_tmp_27
	var __oct_internal_tmp_28 int
	_ = __oct_internal_tmp_28
	var __oct_internal_tmp_29 int
	_ = __oct_internal_tmp_29
	var __oct_internal_tmp_3 int
	_ = __oct_internal_tmp_3
	var __oct_internal_tmp_30 int
	_ = __oct_internal_tmp_30
	var __oct_internal_tmp_31 Main_AccountStatus
	_ = __oct_internal_tmp_31
	var __oct_internal_tmp_32 Main_TransitionDecision
	_ = __oct_internal_tmp_32
	var __oct_internal_tmp_33 bool
	_ = __oct_internal_tmp_33
	var __oct_internal_tmp_34 int
	_ = __oct_internal_tmp_34
	var __oct_internal_tmp_35 int
	_ = __oct_internal_tmp_35
	var __oct_internal_tmp_36 Main_AccountStatus
	_ = __oct_internal_tmp_36
	var __oct_internal_tmp_37 Main_TransitionDecision
	_ = __oct_internal_tmp_37
	var __oct_internal_tmp_38 bool
	_ = __oct_internal_tmp_38
	var __oct_internal_tmp_39 int
	_ = __oct_internal_tmp_39
	var __oct_internal_tmp_4 Main_AccountStatus
	_ = __oct_internal_tmp_4
	var __oct_internal_tmp_40 int
	_ = __oct_internal_tmp_40
	var __oct_internal_tmp_41 Main_AccountStatus
	_ = __oct_internal_tmp_41
	var __oct_internal_tmp_42 Main_TransitionDecision
	_ = __oct_internal_tmp_42
	var __oct_internal_tmp_43 bool
	_ = __oct_internal_tmp_43
	var __oct_internal_tmp_44 int
	_ = __oct_internal_tmp_44
	var __oct_internal_tmp_45 int
	_ = __oct_internal_tmp_45
	var __oct_internal_tmp_46 Main_AccountStatus
	_ = __oct_internal_tmp_46
	var __oct_internal_tmp_47 Main_TransitionDecision
	_ = __oct_internal_tmp_47
	var __oct_internal_tmp_48 bool
	_ = __oct_internal_tmp_48
	var __oct_internal_tmp_49 int
	_ = __oct_internal_tmp_49
	var __oct_internal_tmp_5 Main_TransitionDecision
	_ = __oct_internal_tmp_5
	var __oct_internal_tmp_50 int
	_ = __oct_internal_tmp_50
	var __oct_internal_tmp_51 Main_AccountStatus
	_ = __oct_internal_tmp_51
	var __oct_internal_tmp_52 Main_TransitionDecision
	_ = __oct_internal_tmp_52
	var __oct_internal_tmp_53 bool
	_ = __oct_internal_tmp_53
	var __oct_internal_tmp_54 int
	_ = __oct_internal_tmp_54
	var __oct_internal_tmp_55 int
	_ = __oct_internal_tmp_55
	var __oct_internal_tmp_56 int
	_ = __oct_internal_tmp_56
	var __oct_internal_tmp_57 int
	_ = __oct_internal_tmp_57
	var __oct_internal_tmp_58 Main_AccountStatus
	_ = __oct_internal_tmp_58
	var __oct_internal_tmp_59 Main_TransitionDecision
	_ = __oct_internal_tmp_59
	var __oct_internal_tmp_6 Main_TransitionDecision
	_ = __oct_internal_tmp_6
	var __oct_internal_tmp_60 bool
	_ = __oct_internal_tmp_60
	var __oct_internal_tmp_61 int
	_ = __oct_internal_tmp_61
	var __oct_internal_tmp_62 int
	_ = __oct_internal_tmp_62
	var __oct_internal_tmp_63 Main_AccountStatus
	_ = __oct_internal_tmp_63
	var __oct_internal_tmp_64 Main_TransitionDecision
	_ = __oct_internal_tmp_64
	var __oct_internal_tmp_65 bool
	_ = __oct_internal_tmp_65
	var __oct_internal_tmp_66 int
	_ = __oct_internal_tmp_66
	var __oct_internal_tmp_67 int
	_ = __oct_internal_tmp_67
	var __oct_internal_tmp_68 Main_AccountStatus
	_ = __oct_internal_tmp_68
	var __oct_internal_tmp_69 Main_TransitionDecision
	_ = __oct_internal_tmp_69
	var __oct_internal_tmp_7 bool
	_ = __oct_internal_tmp_7
	var __oct_internal_tmp_70 bool
	_ = __oct_internal_tmp_70
	var __oct_internal_tmp_71 int
	_ = __oct_internal_tmp_71
	var __oct_internal_tmp_72 int
	_ = __oct_internal_tmp_72
	var __oct_internal_tmp_73 Main_AccountStatus
	_ = __oct_internal_tmp_73
	var __oct_internal_tmp_74 Main_TransitionDecision
	_ = __oct_internal_tmp_74
	var __oct_internal_tmp_75 bool
	_ = __oct_internal_tmp_75
	var __oct_internal_tmp_76 int
	_ = __oct_internal_tmp_76
	var __oct_internal_tmp_77 int
	_ = __oct_internal_tmp_77
	var __oct_internal_tmp_78 Main_AccountStatus
	_ = __oct_internal_tmp_78
	var __oct_internal_tmp_79 Main_TransitionDecision
	_ = __oct_internal_tmp_79
	var __oct_internal_tmp_8 int
	_ = __oct_internal_tmp_8
	var __oct_internal_tmp_80 bool
	_ = __oct_internal_tmp_80
	var __oct_internal_tmp_81 int
	_ = __oct_internal_tmp_81
	var __oct_internal_tmp_82 int
	_ = __oct_internal_tmp_82
	var __oct_internal_tmp_83 Main_AccountStatus
	_ = __oct_internal_tmp_83
	var __oct_internal_tmp_84 Main_TransitionDecision
	_ = __oct_internal_tmp_84
	var __oct_internal_tmp_85 bool
	_ = __oct_internal_tmp_85
	var __oct_internal_tmp_86 int
	_ = __oct_internal_tmp_86
	var __oct_internal_tmp_87 int
	_ = __oct_internal_tmp_87
	var __oct_internal_tmp_88 int
	_ = __oct_internal_tmp_88
	var __oct_internal_tmp_89 int
	_ = __oct_internal_tmp_89
	var __oct_internal_tmp_9 int
	_ = __oct_internal_tmp_9
	var __oct_internal_tmp_90 int
	_ = __oct_internal_tmp_90
	var __oct_internal_tmp_91 int
	_ = __oct_internal_tmp_91
	var __oct_internal_tmp_92 Main_AccountStatus
	_ = __oct_internal_tmp_92
	var __oct_internal_tmp_93 Main_TransitionDecision
	_ = __oct_internal_tmp_93
	var __oct_internal_tmp_94 bool
	_ = __oct_internal_tmp_94
	var __oct_internal_tmp_95 int
	_ = __oct_internal_tmp_95
	var __oct_internal_tmp_96 int
	_ = __oct_internal_tmp_96
	var __oct_internal_tmp_97 Main_AccountStatus
	_ = __oct_internal_tmp_97
	var __oct_internal_tmp_98 Main_TransitionDecision
	_ = __oct_internal_tmp_98
	var __oct_internal_tmp_99 bool
	_ = __oct_internal_tmp_99
	var __oct_user_5 int
	_ = __oct_user_5
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = fn_Main_DecideCode(__oct_user_0, __oct_user_2, __oct_user_3, __oct_user_4)
			__oct_user_5 = __oct_internal_tmp_0
			__oct_internal_tmp_1 = (__oct_user_5 == 1)
			if __oct_internal_tmp_1 {
				__oct_internal_pc = 2
			} else {
				__oct_internal_pc = 3
			}
			continue
		case 1:
			return __oct_internal_tmp_6
		case 2:
			__oct_internal_tmp_2 = __oct_user_0.BalanceA
			__oct_internal_tmp_3 = __oct_user_0.BalanceB
			__oct_internal_tmp_4 = __oct_user_0.StatusA
			__oct_internal_tmp_5 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountExists_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_2, __oct_internal_tmp_3, __oct_internal_tmp_4, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_5
			__oct_internal_pc = 1
			continue
		case 3:
			__oct_internal_tmp_7 = (__oct_user_5 == 2)
			if __oct_internal_tmp_7 {
				__oct_internal_pc = 4
			} else {
				__oct_internal_pc = 5
			}
			continue
		case 4:
			__oct_internal_tmp_8 = __oct_user_0.BalanceA
			__oct_internal_tmp_9 = __oct_user_0.BalanceB
			__oct_internal_tmp_10 = __oct_user_0.StatusA
			__oct_internal_tmp_11 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_8, __oct_internal_tmp_9, __oct_internal_tmp_10, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_11
			__oct_internal_pc = 1
			continue
		case 5:
			__oct_internal_tmp_12 = (__oct_user_5 == 3)
			if __oct_internal_tmp_12 {
				__oct_internal_pc = 6
			} else {
				__oct_internal_pc = 7
			}
			continue
		case 6:
			__oct_internal_tmp_13 = __oct_user_0.Amount
			__oct_internal_tmp_14 = __oct_user_0.BalanceB
			__oct_internal_tmp_15 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_Create_tag}, __oct_internal_tmp_13, __oct_internal_tmp_14, Main_AccountStatus{Tag: AccountStatus_Open_tag}, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_15
			__oct_internal_pc = 1
			continue
		case 7:
			__oct_internal_tmp_16 = (__oct_user_5 == 4)
			if __oct_internal_tmp_16 {
				__oct_internal_pc = 8
			} else {
				__oct_internal_pc = 9
			}
			continue
		case 8:
			__oct_internal_tmp_17 = __oct_user_0.BalanceA
			__oct_internal_tmp_18 = __oct_user_0.BalanceB
			__oct_internal_tmp_19 = __oct_user_0.StatusA
			__oct_internal_tmp_20 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_17, __oct_internal_tmp_18, __oct_internal_tmp_19, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_20
			__oct_internal_pc = 1
			continue
		case 9:
			__oct_internal_tmp_21 = (__oct_user_5 == 5)
			if __oct_internal_tmp_21 {
				__oct_internal_pc = 10
			} else {
				__oct_internal_pc = 11
			}
			continue
		case 10:
			__oct_internal_tmp_22 = __oct_user_0.BalanceA
			__oct_internal_tmp_23 = __oct_user_0.BalanceB
			__oct_internal_tmp_24 = __oct_user_0.StatusA
			__oct_internal_tmp_25 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_22, __oct_internal_tmp_23, __oct_internal_tmp_24, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_25
			__oct_internal_pc = 1
			continue
		case 11:
			__oct_internal_tmp_26 = (__oct_user_5 == 6)
			if __oct_internal_tmp_26 {
				__oct_internal_pc = 12
			} else {
				__oct_internal_pc = 13
			}
			continue
		case 12:
			__oct_internal_tmp_27 = __oct_user_0.BalanceA
			__oct_internal_tmp_28 = __oct_user_0.Amount
			__oct_internal_tmp_29 = (__oct_internal_tmp_27 + __oct_internal_tmp_28)
			__oct_internal_tmp_30 = __oct_user_0.BalanceB
			__oct_internal_tmp_31 = __oct_user_0.StatusA
			__oct_internal_tmp_32 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_SetBalance_tag}, __oct_internal_tmp_29, __oct_internal_tmp_30, __oct_internal_tmp_31, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_32
			__oct_internal_pc = 1
			continue
		case 13:
			__oct_internal_tmp_33 = (__oct_user_5 == 7)
			if __oct_internal_tmp_33 {
				__oct_internal_pc = 14
			} else {
				__oct_internal_pc = 15
			}
			continue
		case 14:
			__oct_internal_tmp_34 = __oct_user_0.BalanceA
			__oct_internal_tmp_35 = __oct_user_0.BalanceB
			__oct_internal_tmp_36 = __oct_user_0.StatusA
			__oct_internal_tmp_37 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_34, __oct_internal_tmp_35, __oct_internal_tmp_36, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_37
			__oct_internal_pc = 1
			continue
		case 15:
			__oct_internal_tmp_38 = (__oct_user_5 == 8)
			if __oct_internal_tmp_38 {
				__oct_internal_pc = 16
			} else {
				__oct_internal_pc = 17
			}
			continue
		case 16:
			__oct_internal_tmp_39 = __oct_user_0.BalanceA
			__oct_internal_tmp_40 = __oct_user_0.BalanceB
			__oct_internal_tmp_41 = __oct_user_0.StatusA
			__oct_internal_tmp_42 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_39, __oct_internal_tmp_40, __oct_internal_tmp_41, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_42
			__oct_internal_pc = 1
			continue
		case 17:
			__oct_internal_tmp_43 = (__oct_user_5 == 9)
			if __oct_internal_tmp_43 {
				__oct_internal_pc = 18
			} else {
				__oct_internal_pc = 19
			}
			continue
		case 18:
			__oct_internal_tmp_44 = __oct_user_0.BalanceA
			__oct_internal_tmp_45 = __oct_user_0.BalanceB
			__oct_internal_tmp_46 = __oct_user_0.StatusA
			__oct_internal_tmp_47 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountFrozen_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_44, __oct_internal_tmp_45, __oct_internal_tmp_46, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_47
			__oct_internal_pc = 1
			continue
		case 19:
			__oct_internal_tmp_48 = (__oct_user_5 == 10)
			if __oct_internal_tmp_48 {
				__oct_internal_pc = 20
			} else {
				__oct_internal_pc = 21
			}
			continue
		case 20:
			__oct_internal_tmp_49 = __oct_user_0.BalanceA
			__oct_internal_tmp_50 = __oct_user_0.BalanceB
			__oct_internal_tmp_51 = __oct_user_0.StatusA
			__oct_internal_tmp_52 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InsufficientFunds_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_49, __oct_internal_tmp_50, __oct_internal_tmp_51, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_52
			__oct_internal_pc = 1
			continue
		case 21:
			__oct_internal_tmp_53 = (__oct_user_5 == 11)
			if __oct_internal_tmp_53 {
				__oct_internal_pc = 22
			} else {
				__oct_internal_pc = 23
			}
			continue
		case 22:
			__oct_internal_tmp_54 = __oct_user_0.BalanceA
			__oct_internal_tmp_55 = __oct_user_0.Amount
			__oct_internal_tmp_56 = (__oct_internal_tmp_54 - __oct_internal_tmp_55)
			__oct_internal_tmp_57 = __oct_user_0.BalanceB
			__oct_internal_tmp_58 = __oct_user_0.StatusA
			__oct_internal_tmp_59 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_SetBalance_tag}, __oct_internal_tmp_56, __oct_internal_tmp_57, __oct_internal_tmp_58, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_59
			__oct_internal_pc = 1
			continue
		case 23:
			__oct_internal_tmp_60 = (__oct_user_5 == 12)
			if __oct_internal_tmp_60 {
				__oct_internal_pc = 24
			} else {
				__oct_internal_pc = 25
			}
			continue
		case 24:
			__oct_internal_tmp_61 = __oct_user_0.BalanceA
			__oct_internal_tmp_62 = __oct_user_0.BalanceB
			__oct_internal_tmp_63 = __oct_user_0.StatusA
			__oct_internal_tmp_64 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidWorkflow_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_61, __oct_internal_tmp_62, __oct_internal_tmp_63, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_64
			__oct_internal_pc = 1
			continue
		case 25:
			__oct_internal_tmp_65 = (__oct_user_5 == 13)
			if __oct_internal_tmp_65 {
				__oct_internal_pc = 26
			} else {
				__oct_internal_pc = 27
			}
			continue
		case 26:
			__oct_internal_tmp_66 = __oct_user_0.BalanceA
			__oct_internal_tmp_67 = __oct_user_0.BalanceB
			__oct_internal_tmp_68 = __oct_user_0.StatusA
			__oct_internal_tmp_69 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_66, __oct_internal_tmp_67, __oct_internal_tmp_68, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_69
			__oct_internal_pc = 1
			continue
		case 27:
			__oct_internal_tmp_70 = (__oct_user_5 == 14)
			if __oct_internal_tmp_70 {
				__oct_internal_pc = 28
			} else {
				__oct_internal_pc = 29
			}
			continue
		case 28:
			__oct_internal_tmp_71 = __oct_user_0.BalanceA
			__oct_internal_tmp_72 = __oct_user_0.BalanceB
			__oct_internal_tmp_73 = __oct_user_0.StatusA
			__oct_internal_tmp_74 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_71, __oct_internal_tmp_72, __oct_internal_tmp_73, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_74
			__oct_internal_pc = 1
			continue
		case 29:
			__oct_internal_tmp_75 = (__oct_user_5 == 15)
			if __oct_internal_tmp_75 {
				__oct_internal_pc = 30
			} else {
				__oct_internal_pc = 31
			}
			continue
		case 30:
			__oct_internal_tmp_76 = __oct_user_0.BalanceA
			__oct_internal_tmp_77 = __oct_user_0.BalanceB
			__oct_internal_tmp_78 = __oct_user_0.StatusA
			__oct_internal_tmp_79 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountFrozen_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_76, __oct_internal_tmp_77, __oct_internal_tmp_78, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_79
			__oct_internal_pc = 1
			continue
		case 31:
			__oct_internal_tmp_80 = (__oct_user_5 == 16)
			if __oct_internal_tmp_80 {
				__oct_internal_pc = 32
			} else {
				__oct_internal_pc = 33
			}
			continue
		case 32:
			__oct_internal_tmp_81 = __oct_user_0.BalanceA
			__oct_internal_tmp_82 = __oct_user_0.BalanceB
			__oct_internal_tmp_83 = __oct_user_0.StatusA
			__oct_internal_tmp_84 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InsufficientFunds_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_81, __oct_internal_tmp_82, __oct_internal_tmp_83, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_84
			__oct_internal_pc = 1
			continue
		case 33:
			__oct_internal_tmp_85 = (__oct_user_5 == 17)
			if __oct_internal_tmp_85 {
				__oct_internal_pc = 34
			} else {
				__oct_internal_pc = 35
			}
			continue
		case 34:
			__oct_internal_tmp_86 = __oct_user_0.BalanceA
			__oct_internal_tmp_87 = __oct_user_0.Amount
			__oct_internal_tmp_88 = (__oct_internal_tmp_86 - __oct_internal_tmp_87)
			__oct_internal_tmp_89 = __oct_user_0.BalanceB
			__oct_internal_tmp_90 = __oct_user_0.Amount
			__oct_internal_tmp_91 = (__oct_internal_tmp_89 + __oct_internal_tmp_90)
			__oct_internal_tmp_92 = __oct_user_0.StatusA
			__oct_internal_tmp_93 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_Transfer_tag}, __oct_internal_tmp_88, __oct_internal_tmp_91, __oct_internal_tmp_92, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_93
			__oct_internal_pc = 1
			continue
		case 35:
			__oct_internal_tmp_94 = (__oct_user_5 == 18)
			if __oct_internal_tmp_94 {
				__oct_internal_pc = 36
			} else {
				__oct_internal_pc = 37
			}
			continue
		case 36:
			__oct_internal_tmp_95 = __oct_user_0.BalanceA
			__oct_internal_tmp_96 = __oct_user_0.BalanceB
			__oct_internal_tmp_97 = __oct_user_0.StatusA
			__oct_internal_tmp_98 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_95, __oct_internal_tmp_96, __oct_internal_tmp_97, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_98
			__oct_internal_pc = 1
			continue
		case 37:
			__oct_internal_tmp_99 = (__oct_user_5 == 19)
			if __oct_internal_tmp_99 {
				__oct_internal_pc = 38
			} else {
				__oct_internal_pc = 39
			}
			continue
		case 38:
			__oct_internal_tmp_100 = __oct_user_0.BalanceA
			__oct_internal_tmp_101 = __oct_user_0.BalanceB
			__oct_internal_tmp_102 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_SetStatus_tag}, __oct_internal_tmp_100, __oct_internal_tmp_101, Main_AccountStatus{Tag: AccountStatus_Frozen_tag}, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_102
			__oct_internal_pc = 1
			continue
		case 39:
			__oct_internal_tmp_103 = (__oct_user_5 == 20)
			if __oct_internal_tmp_103 {
				__oct_internal_pc = 40
			} else {
				__oct_internal_pc = 41
			}
			continue
		case 40:
			__oct_internal_tmp_104 = __oct_user_0.BalanceA
			__oct_internal_tmp_105 = __oct_user_0.BalanceB
			__oct_internal_tmp_106 = __oct_user_0.StatusA
			__oct_internal_tmp_107 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_AccountMissing_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_104, __oct_internal_tmp_105, __oct_internal_tmp_106, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_107
			__oct_internal_pc = 1
			continue
		case 41:
			__oct_internal_tmp_108 = (__oct_user_5 == 21)
			if __oct_internal_tmp_108 {
				__oct_internal_pc = 42
			} else {
				__oct_internal_pc = 43
			}
			continue
		case 42:
			__oct_internal_tmp_109 = __oct_user_0.BalanceA
			__oct_internal_tmp_110 = __oct_user_0.BalanceB
			__oct_internal_tmp_111 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Applied_tag}, Main_EffectKind{Tag: EffectKind_SetStatus_tag}, __oct_internal_tmp_109, __oct_internal_tmp_110, Main_AccountStatus{Tag: AccountStatus_Open_tag}, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_111
			__oct_internal_pc = 1
			continue
		case 43:
			__oct_internal_tmp_112 = (__oct_user_5 == 22)
			if __oct_internal_tmp_112 {
				__oct_internal_pc = 44
			} else {
				__oct_internal_pc = 45
			}
			continue
		case 44:
			__oct_internal_tmp_113 = __oct_user_0.BalanceA
			__oct_internal_tmp_114 = __oct_user_0.BalanceB
			__oct_internal_tmp_115 = __oct_user_0.StatusA
			__oct_internal_tmp_116 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidAmount_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_113, __oct_internal_tmp_114, __oct_internal_tmp_115, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_116
			__oct_internal_pc = 1
			continue
		case 45:
			__oct_internal_tmp_117 = (__oct_user_5 == 23)
			if __oct_internal_tmp_117 {
				__oct_internal_pc = 46
			} else {
				__oct_internal_pc = 47
			}
			continue
		case 46:
			__oct_internal_tmp_118 = __oct_user_0.BalanceA
			__oct_internal_tmp_119 = __oct_user_0.BalanceB
			__oct_internal_tmp_120 = __oct_user_0.StatusA
			__oct_internal_tmp_121 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_AwaitingConfirmation_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_118, __oct_internal_tmp_119, __oct_internal_tmp_120, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_121
			__oct_internal_pc = 1
			continue
		case 47:
			__oct_internal_tmp_122 = (__oct_user_5 == 24)
			if __oct_internal_tmp_122 {
				__oct_internal_pc = 48
			} else {
				__oct_internal_pc = 49
			}
			continue
		case 48:
			__oct_internal_tmp_123 = __oct_user_0.BalanceA
			__oct_internal_tmp_124 = __oct_user_0.BalanceB
			__oct_internal_tmp_125 = __oct_user_0.StatusA
			__oct_internal_tmp_126 = fn_Main_Decision(__oct_user_0, true, Main_DecisionReason{Tag: DecisionReason_Cancelled_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_123, __oct_internal_tmp_124, __oct_internal_tmp_125, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_126
			__oct_internal_pc = 1
			continue
		case 49:
			__oct_internal_tmp_127 = __oct_user_0.BalanceA
			__oct_internal_tmp_128 = __oct_user_0.BalanceB
			__oct_internal_tmp_129 = __oct_user_0.StatusA
			__oct_internal_tmp_130 = fn_Main_Decision(__oct_user_0, false, Main_DecisionReason{Tag: DecisionReason_InvalidWorkflow_tag}, Main_EffectKind{Tag: EffectKind_None_tag}, __oct_internal_tmp_127, __oct_internal_tmp_128, __oct_internal_tmp_129, __oct_user_1)
			__oct_internal_tmp_6 = __oct_internal_tmp_130
			__oct_internal_pc = 1
			continue
		}
	}
}

func fn_Main_Main() {
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			return
		}
	}
}

func fn_Main___oct_refine_PositiveAmount(__oct_user_0 int) octResult_Main_PositiveAmount {
	var __oct_internal_tmp_0 bool
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 bool
	_ = __oct_internal_tmp_1
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = (__oct_user_0 > 0)
			__oct_internal_tmp_1 = (!__oct_internal_tmp_0)
			if __oct_internal_tmp_1 {
				__oct_internal_pc = 1
			} else {
				__oct_internal_pc = 2
			}
			continue
		case 1:
			return octResult_Main_PositiveAmount{Err: "refined concept PositiveAmount: amount must be positive", IsErr: true}
		case 2:
			__oct_internal_pc = 3
			continue
		case 3:
			return octResult_Main_PositiveAmount{Value: __oct_user_0}
		}
	}
}

var __octAssertionCount int
