// Code generated by Oct's compiled backend. DO NOT EDIT.
package scheduled

import ()

type octResult_Int struct {
	Value int
	Err   string
	IsErr bool
}

type Scheduler_SchedulerDecisionBoardSnapshot struct {
	Decision int
}

type Scheduler_PersistentParityControllerBoardSnapshot struct {
	OldestEligible bool
	Chosen         int
	Decisions      int
}

type Scheduler_PersistentFairControllerBoardSnapshot struct {
	OldestEligible bool
	HighEligible   bool
	AgedEligible   bool
	BatchEligible  bool
	OldestScore    int
	HighScore      int
	BatchScore     int
	Chosen         int
	Decisions      int
}

type Scheduler_SchedulerOutcome struct {
	Tag     int
	Payload any
}

const (
	SchedulerOutcome_Reject_tag     = 0
	SchedulerOutcome_Wait_tag       = 1
	SchedulerOutcome_Compatible_tag = 2
	SchedulerOutcome_Dispatch_tag   = 3
)

type __octFlowInstance_Int interface {
	__octStep()
	__octActive() string
	__octComplete() bool
	__octResult() (int, bool)
	__octStateHistory() []string
	__octResumeTarget() string
	__octBoardSnapshot() (any, bool)
}

type __octResultFlow_Int struct {
	Value int
	Err   string
	IsErr bool
}

type __octFlow_Scheduler_SchedulerDecision struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       int
	hasResult    bool
	used         int
	capacity     int
	requestClass int
	batchClass   int
	batchCount   int
	maxBatch     int
	board        struct {
		Decision int
	}
}

func fn_Scheduler_SchedulerDecision(used int, capacity int, requestClass int, batchClass int, batchCount int, maxBatch int) __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_SchedulerDecision{}
	__flow.used = used
	__flow.capacity = capacity
	__flow.requestClass = requestClass
	__flow.batchClass = batchClass
	__flow.batchCount = batchCount
	__flow.maxBatch = maxBatch
	return __flow
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Idle"
	case 1:
		return "Observe"
	case 2:
		return "Queue"
	case 3:
		return "BatchReady"
	case 4:
		return "Complete"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_SchedulerDecision) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octBoardSnapshot() (any, bool) {
	return Scheduler_SchedulerDecisionBoardSnapshot{
		Decision: f.board.Decision,
	}, true
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.currentState = 1
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Idle exited without suspend or return")
			}
		case 1:
			switch f.instruction {
			case 0:
				if f.used >= f.capacity {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Reject_tag})
					f.currentState = 4
					f.instruction = 0
					continue
				}
				f.currentState = 2
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Observe exited without suspend or return")
			}
		case 2:
			switch f.instruction {
			case 0:
				if f.batchCount == 0 {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					continue
				}
				if f.requestClass > 1 {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					continue
				}
				if f.requestClass != f.batchClass {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					continue
				}
				f.currentState = 3
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Queue exited without suspend or return")
			}
		case 3:
			switch f.instruction {
			case 0:
				if (f.batchCount + 1) >= f.maxBatch {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Dispatch_tag})
					f.currentState = 4
					f.instruction = 0
					continue
				}
				f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Compatible_tag})
				f.currentState = 4
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state BatchReady exited without suspend or return")
			}
		case 4:
			switch f.instruction {
			case 0:
				f.result = f.board.Decision
				f.hasResult = true
				f.completed = true
				f.currentState = -1
				return
			default:
				panic("runtime invariant violation: flow state Complete exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Scheduler_PersistentParityController struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       int
	hasResult    bool
	utilitySite0 __octScalarUtilitySiteState[int]
	board        struct {
		OldestEligible bool
		Chosen         int
		Decisions      int
	}
}

func fn_Scheduler_PersistentParityController() __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_PersistentParityController{}
	return __flow
}

func (f *__octFlow_Scheduler_PersistentParityController) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PersistentParityController) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_PersistentParityController) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_PersistentParityController) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Scheduler_PersistentParityController) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Scheduler_PersistentParityController) __octBoardSnapshot() (any, bool) {
	return Scheduler_PersistentParityControllerBoardSnapshot{
		OldestEligible: f.board.OldestEligible,
		Chosen:         f.board.Chosen,
		Decisions:      f.board.Decisions,
	}, true
}

func (f *__octFlow_Scheduler_PersistentParityController) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.board.Chosen = __octUtilSelectScalar[int](&f.utilitySite0, 0, 1, []__octUtilCandidate[int]{{Valid: f.board.OldestEligible, Value: 0, Score: 1}}, 4)
				f.instruction++
				continue
			case 1:
				f.board.Decisions = (f.board.Decisions + 1)
				f.instruction++
				continue
			case 2:
				f.instruction++
				return
			case 3:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Decide exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Scheduler_PersistentFairController struct {
	started      bool
	completed    bool
	currentState int
	instruction  int
	result       int
	hasResult    bool
	utilitySite1 __octScalarUtilitySiteState[int]
	board        struct {
		OldestEligible bool
		HighEligible   bool
		AgedEligible   bool
		BatchEligible  bool
		OldestScore    int
		HighScore      int
		BatchScore     int
		Chosen         int
		Decisions      int
	}
}

func fn_Scheduler_PersistentFairController() __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_PersistentFairController{}
	return __flow
}

func (f *__octFlow_Scheduler_PersistentFairController) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PersistentFairController) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_PersistentFairController) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_PersistentFairController) __octStateHistory() []string {
	return nil
}

func (f *__octFlow_Scheduler_PersistentFairController) __octResumeTarget() string {
	return ""
}

func (f *__octFlow_Scheduler_PersistentFairController) __octBoardSnapshot() (any, bool) {
	return Scheduler_PersistentFairControllerBoardSnapshot{
		OldestEligible: f.board.OldestEligible,
		HighEligible:   f.board.HighEligible,
		AgedEligible:   f.board.AgedEligible,
		BatchEligible:  f.board.BatchEligible,
		OldestScore:    f.board.OldestScore,
		HighScore:      f.board.HighScore,
		BatchScore:     f.board.BatchScore,
		Chosen:         f.board.Chosen,
		Decisions:      f.board.Decisions,
	}, true
}

func (f *__octFlow_Scheduler_PersistentFairController) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.board.AgedEligible {
					f.board.Chosen = 2
				} else {
					f.board.Chosen = __octUtilSelectScalar[int](&f.utilitySite1, 25, 2, []__octUtilCandidate[int]{{Valid: f.board.HighEligible, Value: 1, Score: f.board.HighScore}, {Valid: f.board.BatchEligible, Value: 3, Score: f.board.BatchScore}, {Valid: f.board.OldestEligible, Value: 0, Score: f.board.OldestScore}}, 4)
				}
				f.instruction++
				continue
			case 1:
				f.board.Decisions = (f.board.Decisions + 1)
				f.instruction++
				continue
			case 2:
				f.instruction++
				return
			case 3:
				f.currentState = 0
				f.instruction = 0
				continue
			default:
				panic("runtime invariant violation: flow state Decide exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octUtilCandidate[T any] struct {
	Valid bool
	Value T
	Score int
}

type __octScalarUtilitySiteState[T comparable] struct {
	HasCurrent bool
	Current    T
	Score      int
	CommitAge  int
}

func __octUtilSelectScalar[T comparable](site *__octScalarUtilitySiteState[T], hysteresis int, minCommit int, candidates []__octUtilCandidate[T], elseValue T) T {
	next := __octUtilCandidate[T]{}
	for _, candidate := range candidates {
		if candidate.Valid && (!next.Valid || candidate.Score > next.Score) {
			next = candidate
		}
	}
	if !next.Valid {
		next = __octUtilCandidate[T]{Valid: true, Value: elseValue, Score: 0}
	}
	if site.HasCurrent {
		currentStillValid := false
		for _, candidate := range candidates {
			if candidate.Valid && candidate.Value == site.Current {
				currentStillValid = true
				break
			}
		}
		if currentStillValid {
			commitActive := site.CommitAge < minCommit
			hysteresisBlocks := next.Score <= site.Score+hysteresis
			if commitActive || hysteresisBlocks {
				next = __octUtilCandidate[T]{Valid: true, Value: site.Current, Score: site.Score}
			}
		}
	}
	if !site.HasCurrent || site.Current != next.Value {
		*site = __octScalarUtilitySiteState[T]{HasCurrent: true, Current: next.Value, Score: next.Score, CommitAge: 1}
	} else {
		site.Score = next.Score
		site.CommitAge++
	}
	return next.Value
}
func fn_Scheduler_OutcomeCode(__oct_user_0 Scheduler_SchedulerOutcome) int {
	var __oct_internal_tmp_0 bool
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_internal_tmp_2 bool
	_ = __oct_internal_tmp_2
	var __oct_internal_tmp_3 bool
	_ = __oct_internal_tmp_3
	var __oct_internal_tmp_4 bool
	_ = __oct_internal_tmp_4
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = (__oct_user_0.Tag == SchedulerOutcome_Reject_tag)
			if __oct_internal_tmp_0 {
				__oct_internal_pc = 2
			} else {
				__oct_internal_pc = 3
			}
			continue
		case 1:
			return __oct_internal_tmp_1
		case 2:
			__oct_internal_tmp_1 = 0
			__oct_internal_pc = 1
			continue
		case 3:
			__oct_internal_tmp_2 = (__oct_user_0.Tag == SchedulerOutcome_Wait_tag)
			if __oct_internal_tmp_2 {
				__oct_internal_pc = 4
			} else {
				__oct_internal_pc = 5
			}
			continue
		case 4:
			__oct_internal_tmp_1 = 1
			__oct_internal_pc = 1
			continue
		case 5:
			__oct_internal_tmp_3 = (__oct_user_0.Tag == SchedulerOutcome_Compatible_tag)
			if __oct_internal_tmp_3 {
				__oct_internal_pc = 6
			} else {
				__oct_internal_pc = 7
			}
			continue
		case 6:
			__oct_internal_tmp_1 = 2
			__oct_internal_pc = 1
			continue
		case 7:
			__oct_internal_tmp_4 = (__oct_user_0.Tag == SchedulerOutcome_Dispatch_tag)
			if __oct_internal_tmp_4 {
				__oct_internal_pc = 8
			} else {
				__oct_internal_pc = 9
			}
			continue
		case 8:
			__oct_internal_tmp_1 = 3
			__oct_internal_pc = 1
			continue
		case 9:
			panic("non-exhaustive match reached in compiled mode")
		}
	}
}

func fn_Scheduler_Main() int {
	var __oct_internal_tmp_0 __octFlowInstance_Int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_user_0 __octFlowInstance_Int
	_ = __oct_user_0
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = fn_Scheduler_SchedulerDecision(0, 64, 0, 0, 0, 8)
			__oct_user_0 = __oct_internal_tmp_0
			__oct_user_0.__octStep()
			__oct_internal_tmp_1 = 0
			_ = __oct_internal_tmp_1
			return 0
		}
	}
}

var __octAssertionCount int
