// Code generated by Oct's compiled backend. DO NOT EDIT.
package scheduled

import (
	"fmt"
	"reflect"
)

type __octRange struct {
	Start    int
	HasStart bool
	End      int
	HasEnd   bool
	Step     int
	HasStep  bool
}

func __octClone[T any](value T) T {
	cloned := __octCloneValue(reflect.ValueOf(value))
	if !cloned.IsValid() {
		return value
	}
	return cloned.Interface().(T)
}

func __octCloneValue(value reflect.Value) reflect.Value {
	if !value.IsValid() {
		return value
	}
	switch value.Kind() {
	case reflect.Slice:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		out := reflect.MakeSlice(value.Type(), value.Len(), value.Len())
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(__octCloneValue(value.Index(i)))
		}
		return out
	case reflect.Array:
		out := reflect.New(value.Type()).Elem()
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(__octCloneValue(value.Index(i)))
		}
		return out
	case reflect.Struct:
		out := reflect.New(value.Type()).Elem()
		for i := 0; i < value.NumField(); i++ {
			if out.Field(i).CanSet() {
				out.Field(i).Set(__octCloneValue(value.Field(i)))
			}
		}
		return out
	default:
		return value
	}
}

func __octAssignRow[T any](matrix [][]T, row int, rhs []T) {
	if row < 0 || row >= len(matrix) {
		panic(fmt.Sprintf("runtime error: row index %d out of bounds for array with %d rows", row, len(matrix)))
	}
	if len(rhs) != len(matrix[row]) {
		panic(fmt.Sprintf("runtime error: row length mismatch: expected %d, got %d", len(matrix[row]), len(rhs)))
	}
	matrix[row] = __octClone(rhs)
}

type octResult_Int struct {
	Value int
	Err   string
	IsErr bool
}

type Scheduler_SchedulerDecisionBoardSnapshot struct {
	Decision int
}

type Scheduler_PolicyHysteresisProbeBoardSnapshot struct {
	Tick   int
	Chosen int
}

type Scheduler_PolicyMinCommitProbeBoardSnapshot struct {
	Tick   int
	Chosen int
}

type Scheduler_SchedulerOutcome struct {
	Tag     int
	Payload any
}

const (
	SchedulerOutcome_Reject_tag     = 0
	SchedulerOutcome_Wait_tag       = 1
	SchedulerOutcome_Compatible_tag = 2
	SchedulerOutcome_Dispatch_tag   = 3
)

type __octFlowInstance_Int interface {
	__octStep()
	__octActive() string
	__octComplete() bool
	__octResult() (int, bool)
	__octStateHistory() []string
	__octResumeTarget() string
	__octBoardSnapshot() (any, bool)
}

type __octResultFlow_Int struct {
	Value int
	Err   string
	IsErr bool
}

type __octFlow_Scheduler_SchedulerDecision struct {
	started         bool
	completed       bool
	currentState    int
	instruction     int
	result          int
	hasResult       bool
	history         []string
	hasResumeTarget bool
	resumeTarget    int
	used            int
	capacity        int
	requestClass    int
	batchClass      int
	batchCount      int
	maxBatch        int
	board           struct {
		Decision int
	}
}

func fn_Scheduler_SchedulerDecision(used int, capacity int, requestClass int, batchClass int, batchCount int, maxBatch int) __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_SchedulerDecision{}
	__flow.used = used
	__flow.capacity = capacity
	__flow.requestClass = requestClass
	__flow.batchClass = batchClass
	__flow.batchCount = batchCount
	__flow.maxBatch = maxBatch
	return __flow
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Idle"
	case 1:
		return "Observe"
	case 2:
		return "Queue"
	case 3:
		return "BatchReady"
	case 4:
		return "Complete"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_SchedulerDecision) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octStateHistory() []string {
	out := make([]string, len(f.history))
	copy(out, f.history)
	return out
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octStateName(id int) string {
	switch id {
	case 0:
		return "Idle"
	case 1:
		return "Observe"
	case 2:
		return "Queue"
	case 3:
		return "BatchReady"
	case 4:
		return "Complete"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octResumeTarget() string {
	if !f.hasResumeTarget {
		return ""
	}
	return f.__octStateName(f.resumeTarget)
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octBoardSnapshot() (any, bool) {
	return Scheduler_SchedulerDecisionBoardSnapshot{
		Decision: f.board.Decision,
	}, true
}

func (f *__octFlow_Scheduler_SchedulerDecision) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
		f.history = append(f.history, "Idle")
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.currentState = 1
				f.instruction = 0
				f.history = append(f.history, "Observe")
				continue
			default:
				panic("runtime invariant violation: flow state Idle exited without suspend or return")
			}
		case 1:
			switch f.instruction {
			case 0:
				if f.used >= f.capacity {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Reject_tag})
					f.currentState = 4
					f.instruction = 0
					f.history = append(f.history, "Complete")
					continue
				}
				f.currentState = 2
				f.instruction = 0
				f.history = append(f.history, "Queue")
				continue
			default:
				panic("runtime invariant violation: flow state Observe exited without suspend or return")
			}
		case 2:
			switch f.instruction {
			case 0:
				if f.batchCount == 0 {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					f.history = append(f.history, "Complete")
					continue
				}
				if f.requestClass > 1 {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					f.history = append(f.history, "Complete")
					continue
				}
				if f.requestClass != f.batchClass {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Wait_tag})
					f.currentState = 4
					f.instruction = 0
					f.history = append(f.history, "Complete")
					continue
				}
				f.currentState = 3
				f.instruction = 0
				f.history = append(f.history, "BatchReady")
				continue
			default:
				panic("runtime invariant violation: flow state Queue exited without suspend or return")
			}
		case 3:
			switch f.instruction {
			case 0:
				if (f.batchCount + 1) >= f.maxBatch {
					f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Dispatch_tag})
					f.currentState = 4
					f.instruction = 0
					f.history = append(f.history, "Complete")
					continue
				}
				f.board.Decision = fn_Scheduler_OutcomeCode(Scheduler_SchedulerOutcome{Tag: SchedulerOutcome_Compatible_tag})
				f.currentState = 4
				f.instruction = 0
				f.history = append(f.history, "Complete")
				continue
			default:
				panic("runtime invariant violation: flow state BatchReady exited without suspend or return")
			}
		case 4:
			switch f.instruction {
			case 0:
				f.result = f.board.Decision
				f.hasResult = true
				f.completed = true
				f.currentState = -1
				return
			default:
				panic("runtime invariant violation: flow state Complete exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Scheduler_UtilityDecision struct {
	started         bool
	completed       bool
	currentState    int
	instruction     int
	result          int
	hasResult       bool
	history         []string
	hasResumeTarget bool
	resumeTarget    int
	utilitySites    map[int]__octUtilitySiteState
	legal           bool
	priority        int
	ageMicros       int
	batchCount      int
	maxBatch        int
}

func fn_Scheduler_UtilityDecision(legal bool, priority int, ageMicros int, batchCount int, maxBatch int) __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_UtilityDecision{}
	__flow.utilitySites = map[int]__octUtilitySiteState{}
	__flow.legal = legal
	__flow.priority = priority
	__flow.ageMicros = ageMicros
	__flow.batchCount = batchCount
	__flow.maxBatch = maxBatch
	return __flow
}

func (f *__octFlow_Scheduler_UtilityDecision) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Eligibility"
	case 1:
		return "Rank"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_UtilityDecision) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_UtilityDecision) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_UtilityDecision) __octStateHistory() []string {
	out := make([]string, len(f.history))
	copy(out, f.history)
	return out
}

func (f *__octFlow_Scheduler_UtilityDecision) __octStateName(id int) string {
	switch id {
	case 0:
		return "Eligibility"
	case 1:
		return "Rank"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_UtilityDecision) __octResumeTarget() string {
	if !f.hasResumeTarget {
		return ""
	}
	return f.__octStateName(f.resumeTarget)
}

func (f *__octFlow_Scheduler_UtilityDecision) __octBoardSnapshot() (any, bool) {
	return nil, false
}

func (f *__octFlow_Scheduler_UtilityDecision) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
		f.history = append(f.history, "Eligibility")
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				if f.legal == false {
					f.result = 1
					f.hasResult = true
					f.completed = true
					f.currentState = -1
					return
				}
				f.currentState = 1
				f.instruction = 0
				f.history = append(f.history, "Rank")
				continue
			default:
				panic("runtime invariant violation: flow state Eligibility exited without suspend or return")
			}
		case 1:
			switch f.instruction {
			case 0:
				f.result = __octUtilSelect[int](f.utilitySites, 0, 8, 3, []__octUtilCandidate[int]{{Valid: (f.ageMicros >= 5000), Value: 2, Score: (300 + f.ageMicros)}, {Valid: (f.batchCount > 1), Value: 3, Score: (200 + f.batchCount)}, {Valid: ((f.batchCount < f.maxBatch) && (f.ageMicros < 2000)), Value: 1, Score: 150}, {Valid: true, Value: 0, Score: (100 + (f.priority * 10))}}, 0)
				f.hasResult = true
				f.completed = true
				f.currentState = -1
				return
			default:
				panic("runtime invariant violation: flow state Rank exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Scheduler_PolicyHysteresisProbe struct {
	started         bool
	completed       bool
	currentState    int
	instruction     int
	result          int
	hasResult       bool
	history         []string
	hasResumeTarget bool
	resumeTarget    int
	utilitySites    map[int]__octUtilitySiteState
	clearWin        bool
	board           struct {
		Tick   int
		Chosen int
	}
}

func fn_Scheduler_PolicyHysteresisProbe(clearWin bool) __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_PolicyHysteresisProbe{}
	__flow.utilitySites = map[int]__octUtilitySiteState{}
	__flow.clearWin = clearWin
	return __flow
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octStateHistory() []string {
	out := make([]string, len(f.history))
	copy(out, f.history)
	return out
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octStateName(id int) string {
	switch id {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octResumeTarget() string {
	if !f.hasResumeTarget {
		return ""
	}
	return f.__octStateName(f.resumeTarget)
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octBoardSnapshot() (any, bool) {
	return Scheduler_PolicyHysteresisProbeBoardSnapshot{
		Tick:   f.board.Tick,
		Chosen: f.board.Chosen,
	}, true
}

func (f *__octFlow_Scheduler_PolicyHysteresisProbe) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
		f.history = append(f.history, "Decide")
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.board.Chosen = __octUtilSelect[int](f.utilitySites, 1, 8, 1, []__octUtilCandidate[int]{{Valid: true, Value: 1, Score: 60}, {Valid: (f.board.Tick > 0), Value: 2, Score: func() int {
					if f.clearWin {
						return 80
					}
					return 65
				}()}}, 0)
				f.instruction++
				continue
			case 1:
				if f.board.Tick == 1 {
					f.result = f.board.Chosen
					f.hasResult = true
					f.completed = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 2:
				f.board.Tick = (f.board.Tick + 1)
				f.instruction++
				continue
			case 3:
				f.currentState = 0
				f.instruction = 0
				f.history = append(f.history, "Decide")
				continue
			default:
				panic("runtime invariant violation: flow state Decide exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

type __octFlow_Scheduler_PolicyMinCommitProbe struct {
	started         bool
	completed       bool
	currentState    int
	instruction     int
	result          int
	hasResult       bool
	history         []string
	hasResumeTarget bool
	resumeTarget    int
	utilitySites    map[int]__octUtilitySiteState
	board           struct {
		Tick   int
		Chosen int
	}
}

func fn_Scheduler_PolicyMinCommitProbe() __octFlowInstance_Int {
	__flow := &__octFlow_Scheduler_PolicyMinCommitProbe{}
	__flow.utilitySites = map[int]__octUtilitySiteState{}
	return __flow
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octComplete() bool { return f.completed }

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octStateHistory() []string {
	out := make([]string, len(f.history))
	copy(out, f.history)
	return out
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octStateName(id int) string {
	switch id {
	case 0:
		return "Decide"
	default:
		return ""
	}
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octResumeTarget() string {
	if !f.hasResumeTarget {
		return ""
	}
	return f.__octStateName(f.resumeTarget)
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octBoardSnapshot() (any, bool) {
	return Scheduler_PolicyMinCommitProbeBoardSnapshot{
		Tick:   f.board.Tick,
		Chosen: f.board.Chosen,
	}, true
}

func (f *__octFlow_Scheduler_PolicyMinCommitProbe) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
		f.history = append(f.history, "Decide")
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.board.Chosen = __octUtilSelect[int](f.utilitySites, 2, 0, 3, []__octUtilCandidate[int]{{Valid: true, Value: 1, Score: 60}, {Valid: (f.board.Tick > 0), Value: 2, Score: 100}}, 0)
				f.instruction++
				continue
			case 1:
				if f.board.Tick == 1 {
					f.result = f.board.Chosen
					f.hasResult = true
					f.completed = true
					f.currentState = -1
					return
				}
				f.instruction++
				continue
			case 2:
				f.board.Tick = (f.board.Tick + 1)
				f.instruction++
				continue
			case 3:
				f.currentState = 0
				f.instruction = 0
				f.history = append(f.history, "Decide")
				continue
			default:
				panic("runtime invariant violation: flow state Decide exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

func __octIntArrayToFloat(values []int) []float64 {
	out := make([]float64, len(values))
	for i, value := range values {
		out[i] = float64(value)
	}
	return out
}

type __octUtilitySiteState struct {
	HasCurrent bool
	Current    any
	Score      int
	CommitAge  int
}

type __octUtilCandidate[T any] struct {
	Valid bool
	Value T
	Score int
}

func __octUtilSelect[T any](sites map[int]__octUtilitySiteState, siteID int, hysteresis int, minCommit int, candidates []__octUtilCandidate[T], elseValue T) T {
	valid := make([]__octUtilCandidate[T], 0, len(candidates))
	for _, c := range candidates {
		if c.Valid {
			valid = append(valid, c)
		}
	}
	next := __octUtilCandidate[T]{Valid: true, Value: elseValue, Score: 0}
	if len(valid) > 0 {
		next = valid[0]
		for _, c := range valid[1:] {
			if c.Score > next.Score {
				next = c
			}
		}
	}
	site := sites[siteID]
	if site.HasCurrent {
		currentStillValid := false
		for _, c := range valid {
			if reflect.DeepEqual(c.Value, site.Current) {
				currentStillValid = true
				break
			}
		}
		if currentStillValid {
			commitActive := site.CommitAge < minCommit
			hysteresisBlocks := next.Score <= site.Score+hysteresis
			if commitActive || hysteresisBlocks {
				next = __octUtilCandidate[T]{Valid: true, Value: site.Current.(T), Score: site.Score}
			}
		}
	}
	if !site.HasCurrent || !reflect.DeepEqual(site.Current, next.Value) {
		sites[siteID] = __octUtilitySiteState{HasCurrent: true, Current: next.Value, Score: next.Score, CommitAge: 1}
	} else {
		site.Score = next.Score
		site.CommitAge++
		sites[siteID] = site
	}
	return next.Value
}
func fn_Scheduler_OutcomeCode(__oct_user_0 Scheduler_SchedulerOutcome) int {
	var __oct_internal_tmp_0 bool
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_internal_tmp_2 bool
	_ = __oct_internal_tmp_2
	var __oct_internal_tmp_3 bool
	_ = __oct_internal_tmp_3
	var __oct_internal_tmp_4 bool
	_ = __oct_internal_tmp_4
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = (__oct_user_0.Tag == SchedulerOutcome_Reject_tag)
			if __oct_internal_tmp_0 {
				__oct_internal_pc = 2
			} else {
				__oct_internal_pc = 3
			}
			continue
		case 1:
			return __oct_internal_tmp_1
		case 2:
			__oct_internal_tmp_1 = 0
			__oct_internal_pc = 1
			continue
		case 3:
			__oct_internal_tmp_2 = (__oct_user_0.Tag == SchedulerOutcome_Wait_tag)
			if __oct_internal_tmp_2 {
				__oct_internal_pc = 4
			} else {
				__oct_internal_pc = 5
			}
			continue
		case 4:
			__oct_internal_tmp_1 = 1
			__oct_internal_pc = 1
			continue
		case 5:
			__oct_internal_tmp_3 = (__oct_user_0.Tag == SchedulerOutcome_Compatible_tag)
			if __oct_internal_tmp_3 {
				__oct_internal_pc = 6
			} else {
				__oct_internal_pc = 7
			}
			continue
		case 6:
			__oct_internal_tmp_1 = 2
			__oct_internal_pc = 1
			continue
		case 7:
			__oct_internal_tmp_4 = (__oct_user_0.Tag == SchedulerOutcome_Dispatch_tag)
			if __oct_internal_tmp_4 {
				__oct_internal_pc = 8
			} else {
				__oct_internal_pc = 9
			}
			continue
		case 8:
			__oct_internal_tmp_1 = 3
			__oct_internal_pc = 1
			continue
		case 9:
			panic("non-exhaustive match reached in compiled mode")
		}
	}
}

func fn_Scheduler_Main() int {
	var __oct_internal_tmp_0 __octFlowInstance_Int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_user_0 __octFlowInstance_Int
	_ = __oct_user_0
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = fn_Scheduler_SchedulerDecision(0, 64, 0, 0, 0, 8)
			__oct_user_0 = __oct_internal_tmp_0
			__oct_user_0.__octStep()
			__oct_internal_tmp_1 = 0
			_ = __oct_internal_tmp_1
			return 0
		}
	}
}

var __octAssertionCount int
